data = {
"ma":{"Pays":"Maroc","Position":"légaliste"},
"dz":{"Pays":"Algérie","Position":"anti-intervention"},
"tn":{"Pays":"Tunisie","Position":"anti-intervention"},
"ly":{"Pays":"Libye","Position":"interventionniste"},
"eg":{"Pays":"Egypte","Position":"anti-intervention"},
"lb":{"Pays":"Liban","Position":"anti-intervention"},
"jo":{"Pays":"Jordanie","Position":"interventionniste"},
"sy":{"Pays":"Syrie","Position":"pays cible"},
"iq":{"Pays":"Irak","Position":"anti-intervention"},
"sa":{"Pays":"Arabie Saoudite","Position":"interventionniste"},
"bh":{"Pays":"Bahreïn","Position":"interventionniste"},
"kw":{"Pays":"Koweït","Position":"interventionniste"},
"qa":{"Pays":"Qatar","Position":"interventionniste"},
"ae":{"Pays":"Emirats Arabes Unis","Position":"interventionniste"},
"om":{"Pays":"Oman","Position":"légaliste"},
"be":{"Pays":"Belgique","Position":"légaliste"},
"nl":{"Pays":"Pays-Bas","Position":"légaliste"},
"ye":{"Pays":"Yémen","Position":"légaliste"},
"tr":{"Pays":"Turquie","Position":"interventionniste"},
"in":{"Pays":"Inde","Position":"légaliste"},
"br":{"Pays":"Brésil","Position":"légaliste"},
"ar":{"Pays":"Argentine","Position":"anti-intervention"},
"mx":{"Pays":"Mexique","Position":"légaliste"},
"za":{"Pays":"Afrique du Sud","Position":"anti-intervention"},
"kr":{"Pays":"Corée du Sud","Position":"légaliste"},
"id":{"Pays":"Indonésie","Position":"légaliste"},
"jp":{"Pays":"Japon","Position":"interventionniste"},
"us":{"Pays":"Etats-Unis","Position":"interventionniste"},
"ca":{"Pays":"Canada","Position":"interventionniste"},
"fr":{"Pays":"France","Position":"interventionniste"},
"gb":{"Pays":"Royaume-Uni","Position":"légaliste"},
"de":{"Pays":"Allemagne","Position":"légaliste"},
"it":{"Pays":"Italie","Position":"légaliste"},
"pl":{"Pays":"Pologne","Position":"légaliste"},
"es":{"Pays":"Espagne","Position":"légaliste"},
"ru":{"Pays":"Russie","Position":"anti-intervention"},
"cn":{"Pays":"Chine","Position":"anti-intervention"},
"au":{"Pays":"Australie","Position":"interventionniste"}
}