var deputes = {
  "aaData" : [
  ["ACCOYER","Délégation générale de l'Alliance Française ","Brésil",20000,"185-02","Coopération culturelle et promotion du français","Assemblée nationale",2011],
["ACCOYER","Echange Sahel",null,10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["AESCHLIMANN","Rotary Club d'Asnières",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["ANCIAUX","Tout dans la 4L",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["ANTIER                 (N)","L'ENVOL - centre médicalisé de loisirs en France pour enfants européens",null,60000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["ARTHUIS","Ambassade de France en Russie","Russie",40000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["ARTHUIS","Consulat de Murcie","Espagne",5000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["ASSOULINE          (N)","Réunion-Dagana","Sénégal",20000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["AURILLAC            (N)","DEFAP - \nService protestant de mission",null,50000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["AURILLAC            (N)","Les Mains Ouvertes               ","Vietnam",40000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["BATTISTEL","Parrainage enfants Calcutta","Inde",1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["BEL","Cuba Coopération","Cuba",15000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["BIGNON","Les 4L du Cœur",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["BOTREL                (N)","Tansab'eau              PUIT POUR UN VILLAGE","Burkina Faso",1000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["BOURRAGUE         (N)","Coup de Soleil          A LA RENCONTRE DU MAGHREB",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["BOUVARD             (N)","Entente La Gacilly-Diapaga         ","Burkina Faso",3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["BOUVARD  Loïc          (N)","Association pour la Solidarité et  la Promotion des \nMitsamiouliens  en France (ASPMF)   GRANDE COMORE","Comores",10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["BOYER                   (N)","La Flamme d'Harmattan",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["BRANGET              (N)","Vel'Horizon Samson   ENFANTS HOSPITALISES AU CHU DE BESANCON",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["BRANGET              (N)","Brulard Ensemble        EPICERIE SOCIALE A BESANCON",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["BRARD","AFAK-Asso fr d'appui au développement de la région de Kayes (Mali)",null,95000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["BRUNEL","Echanges internationaux pour le développement et la coopération (ECIDEC)\nCOLLECTEUR D'EPARGNE SOLIDAIRE - RESEAU \"COUP DE POUCE\" ",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["BRUNEL","Association des Khmers de Bussy-Saint-Georges (AKB)","Cambodge",5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["BRUNEL","Association franco-haïtienne (Roissy-en-Brie) - Seine et Marne","Haïti",3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["CALVET","Comité départemental coopération décentralisée    (CDCD) {+ IRLES  1.000 \u20ac }                   ",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["CALVET","Soler Sénégal Soleil","Sénégal",2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["CALVET","Pezilla Solidarité","Madagascar",1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["CAMBON              (N)","Lycée Marc Chagall de Tel Aviv  COLLEGE","Israël",15000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["CANTEGRIT","Courrier Australien                                  ","Australie",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["CANTEGRIT","Ecole française de Vancouver\n Ecole française internationale - NORTH VANCOUVER","Canada",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["CANTEGRIT","Hôpital Saint-Louis d'Alep","Syrie",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["CANTEGRIT","Association SOS international  \"SOS PAPA INTERNATIONAL\"",null,10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["CANTEGRIT","Assocation Haïti Partenaires France Europe","Haïti",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["CANTEGRIT","Société d'entraide de la Légion d'honneur Caracas","Vénézuela",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["CANTEGRIT","Société d'histoire de l'Ile Maurice","Ile MAURICE",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["CANTEGRIT","Société de l'hôpital Notre Dame de la Paix à Kobayat ","Liban",20000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["CARAYON","Les Enfants de Tana-Maza",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["CARREZ","Citées Unies France",null,50000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["CERISIER BEN GUIGA","Amis de la french ABC   AUX Etats-Unis MAIS RIB EN France","Etats-Unis",20000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["CERISIER BEN GUIGA","Lycée franco costaricien               ","Costa Rica",17500,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["CERISIER BEN GUIGA","Association Véronique                  en France                                    ",null,30000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["CHEVENEMENT   Prés.","Fondation Res Publica",null,50000,"185-04","Diplomatie culturelle et d'influence - Attractivité et recherche","Assemblée nationale",2011],
["CHEVENEMENT   Prés.","Amendement parlementaire",null,10000,151,"Français de l'étranger et affaires consulaires",null,2011],
["CHOSSY              (N)","Association franco-camerounaise BIAGNE","Cameroun",10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["CHRIST                (N)","Association de charité Sainte-Véronique                                                  ",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["CINIERI                 (N)","Easy smile",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["CINIERI                 (N)","Jumelage Sunset-St Paul en Cornillon",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["COCHET","Association pour les échanges et la coopération entre Lyon et Erevan","Arménie",1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["COINTAT","Chambre franco-centroaméricaine      ","Costa Rica",12500,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["COINTAT","Lycée franco-costaricien             ","Costa Rica",22918,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["COINTAT","Lycée français Jules Verne   ","Guatemala",30400,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["COINTAT","Collège des frères de Jaffa     ","Israël",20000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["COINTAT          + frassa","Femmes de la Méditerrannée   LYCEE Français DE MADRID              ","Espagne",11000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["COINTAT        + ferrand","Terre de Talents - Projet d'avenir ",null,2182,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["COINTAT","Courrier Australien      ","Australie",1000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["COPE                     (N)","Moldavenir                                           ","Moldavie",4000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["COUSIN","Sainte Thérèse de l'Enfant Jésus                                               ",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["COUSIN","Sambava Développement                        ","Madagascar",1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["CROZON","Association des Nigériens et amis du Niger en Rhône (ANAN)","Niger",5000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["CROZON","AFPS - Association France Palestine Solidarité","Palestine",5000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["CUVILLIER             (N)"," BOULOGNE ECHANGES INTERNATIONAUX",null,10000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["DE LA VERPILLIERE (N)","Association Eau Soleil",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["DE RUGY                 (N)","Association ARCADE",null,4000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["DECOOL                  (N)","Solidajeunes",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["DEGAUCHY","Unboldair",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["DEL PICCHIA","Lycée Jean Giono de Turin          ","Italie",29000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DEL PICCHIA","Alliance française de la Nouvelle-Orléans","Etats-Unis",8000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DEL PICCHIA","Alliance française de Dallas","Etats-Unis",5000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DEL PICCHIA","French American Charter School de New York        ","Etats-Unis",11000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DEL PICCHIA","Lycée français Charles de Gaulle d'Ankara             ","Turquie",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DEL PICCHIA","Association Al Amal ciné-club au Maroc","Maroc",3000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DEL PICCHIA","Association française du Renouveau d'Abidjan","Côte d'Ivoire",2000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["DEL PICCHIA","Maison de retraite d'Antsirabe en Madagascar","Madagascar",17000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["DEL PICCHIA","Association de bienfaisance de Tel Aviv","Israël",20000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["DESCOEUR","Song-Taaba-France-Cantal-Burkina                                                     ","Burkina Faso",2500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["DESCOEUR","Collectif semaine solidarité internationale",null,1100,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["DESESSARD            (N)","Afrique agri solaire",null,4000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["DIARD                      (N)","Terre des enfants",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["DIONIS DU SEJOUR","Naître au Cameroun","Cameroun",2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["DIONIS DU SEJOUR","Handicap Nord Sud",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["DU LUART","Réseau des alliances françaises et médiathèque du Brésil ","Brésil",30000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["DUMAS","AMISTAD   (reconstruction école à Cuba)","Cuba",12000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["DUMONT                 (N)","Association REAGIR - Agir Ensemble      ",null,1000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["DUMONT                 (N)","Association Amitié Solidarité Tikhvine  MONASTERE EN RUSSIE ","Russie",1500,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["DUPONT                  (N)","Association pour la francophonie de la bande de Gaza (domiciliée à Marseille)\nMEDITERRANEE SOLIDARITE","Palestine",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["DUPUY       Présidente","Association ST2S@ctions",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["DURAND","UNICEF    ",null,1000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["DUVERNOIS","ADIFLOR",null,80000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["DUVERNOIS","Fondation Albert Schweitzer                               ","Gabon",1500,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Ecole Charbonnages Gabon                                 ","Gabon",2000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Cimetière de civils français à Boulbinet                   ","Guinée",1000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Cimetière de civils français à Annaba -   ","Algérie",2000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Ecole Paul Langevin - Côte d'Ivoire                                       ","Côte d'Ivoire",6000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Petit Lotus Bleu - Chine   ","Chine",1500,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Shanghaï Young Bakers Chine                  ","Chine",1500,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Lycée français de Pondichéry                                        ","Inde",5000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Société mutuelle créole - Pondichéry                      ","Inde",9000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Centre francophone Quérétaro                             ","Mexique",2000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Alliance française de Xelapa                               ","Mexique",2000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Alliance française Haïti                                                         ","Haïti",3500,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Boston Ecole internationale                             ","Etats-Unis",4000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Association EFGH - Houston (programme FLAM)","Etats-Unis",4000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Café Littéraire - (publication d'un livre)                 ","Danemark",2000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["DUVERNOIS","Comité d'aide aux Français sinistrés de l'Aquila        ","Italie",3000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["ERHEL                    (N)","Association Armor Goëlo Solidarité Taghrate    ",null,3000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["FAVENNEC","aide au développement de Boussé","Burkina Faso",1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["FAVENNEC","Trait d'Union",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["FERRAND","Alliance française de Monte Cristi             ","Rép. Dominicaine",15000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["FERRAND","Ecole française Jules Verne à Helsinki -                               ","Finlande",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["FERRAND","Ecole française du Maine                                                 ","Etats-Unis",8500,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["FERRAND","Racines françaises au Mexique                      ","Mexique",16500,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["FERRAND","Société franco-allemande de Bayreuth                       ","Allemagne",3000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["FERRAND","Terre de Talents - Projet d'avenir   ",null,10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["FERRAND","Institut franco-allemand d'Erlangen                                                                        ","Allemagne",2000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["FERRAND","Frenz School Inc. - Auckland                          ","Nouvelle Zélande",5000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["FERRAND","Ecoles françaises de Melbourne                    ","Australie",5000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["FERRAND","Foyer français du troisième âge à Santiago du Chili                       ","Chili",15000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["FERRAND","Association française d'entaide du Cap              ","Afrique du Sud",5000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["FERRAND","Société française de bienfaisance de Johannesbourg (SFBJ)        ","Afrique du Sud",5000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["FERRAND","Centre Charles Péguy - Londres                                                ","Grande-Bretagne",15000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["FERRAND","Association des familles franco-chinoises de Shanghai (AFFC)     ","Chine",5000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["FIORASO","Association FEMOCA",null,1000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["FOLLIOT","Aide au développement Sidobre-Bénin (ADESIBE)","Bénin",1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["FORT                    (N)","Association SITCH",null,4000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["FOUCAUD","Les amis du Monde                                                     ",null,1000,"209-02","Développement - Coopération bilatérale","Sénat",2011],
["FOUCAUD","Projet CISAL                                                                                  ",null,5000,"209-02","Développement - Coopération bilatérale","Sénat",2011],
["FOUCAUD","Les Amis de Fort Dauphin                                                       ",null,1000,"209-02","Développement - Coopération bilatérale","Sénat",2011],
["FRASSA","Fondation \"La Voie Lactée\"- ","Haïti",18000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["FRASSA","Ecole primaire \"Francoperuano\" du Callao (PEROU) -","Pérou",5000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["FRASSA","Institut franco-japonais de Tokyo (JAPON) ","Japon",38000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["FRASSA","Association des parents d'élèves du Kansai (JAPON) ","Japon",12000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["FRASSA","Clinique de Gamkalley à Niamey (NIGER) ","Niger",8000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["FRASSA","Lycée français de Madrid   projet \"femmes de la Méditerranée\") -     ","Espagne",19000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["FRASSA","Lycée français Victor Hugo de Francfort","Allemagne",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["GARRIAUD MAYLAM","Centre Estel (Association de bienfaisance à Dakar) ","Sénégal",5000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["GARRIAUD MAYLAM","UFE Mexique","Mexique",12000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["GARRIAUD MAYLAM","Société française de bienfaisance 14 de Julho","Brésil",3000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["GARRIAUD MAYLAM","Collège Voltaire à Berlin","Allemagne",15100,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["GARRIAUD MAYLAM","Ecole Jules Verne à Helsinki","Finlande",4400,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["GARRIAUD MAYLAM","Lycée Nahr Ibrahim               ","Liban",20000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["GARRIAUD MAYLAM","Ecole Saint-Exupéry de Saint-Louis","Sénégal",8300,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["GARRIAUD MAYLAM","Institut culturel français à Dakar","Sénégal",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["GARRIAUD MAYLAM","Lycée Gustave Flaubert de la Marsa ","Tunisie",37200,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["GARRIAUD MAYLAM","Alliances françaises du Chili","Chili",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["GAUBERT","Association ARMOR MEKONG",null,5000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["GEOFFROY            (N)","Rotary Club de Mormant centre Brie",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GISCARD D'ESTAING L.","Comité catholique contre la faim et pour le développement  CCFD-Terre solidaire\n  ",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GISCARD D'ESTAING L.","UNMFREO",null,1750,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GISCARD D'ESTAING L.","ARCADE -CHAMALIERES  Appui aux activités",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GISCARD D'ESTAING L.","AUNOCADEV Appui aux activités",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GISCARD D'ESTAING V.","Institut pour la Démocratie en Europe",null,100000,"105-02","Action européenne","Assemblée nationale",2011],
["GIULIANI","Fondation Robert Schuman",null,100000,"105-02","Action européenne","Assemblée nationale",2011],
["GONNOT                (N)","Association l'Homme par l'Homme pour l'Homme",null,10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GOSSELIN","Les enfants du Soleil",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GOUJON                 (N)","Aurore",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GRALL                   (N)","Association coopération solidarité internationale 56",null,4500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GROMMERCH        (N)","Boubacar Narcisse",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GROSPERRIN          (N)","4L du soleil",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GROSPERRIN          (N)","Association du Riz pour Apprendre",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GROSPERRIN          (N)","Course autour du monde",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GUEGOT                 (N)","Les Enfants du saloum","Sénégal",2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["GUERRY","Lycée français de Saint-Exupéry de Brazzaville","Congo",6000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["GUERRY","Association \"Provinces de France au Maroc\" - CASABLANCE -","Maroc",20000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["GUERRY","ONG Gandeepam - ","Inde",15000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["GUERRY","Fondation mondiale recherche Sida - ASSOCIATION DE LUC MONTAGNIER ",null,48000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["GUILLOTEAU","Bénin Découvertes pour la coopération et le développement","Bénin",1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["HAVARD","FOJEP",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["HAVARD","France HUMANITAIRE","France",5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["HAVARD","A.S.F. Amour Sans Frontière",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["HOSTALIER          (N)","Les Amis de Béthanie                                                                   ","Tchad",5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["HOSTALIER          (N)","Association Terre d'Errance Steenvoorde","France",2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["HOUSSIN               (N)","Marquette Solidarité",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["HUE               Prés. ","Fondation Gabriel Péri",null,160000,"185-04","Diplomatie culturelle et d'influence - Attractivité et recherche","Assemblée nationale",2011],
["HUYGHE                (N)","Habourdin Humanitaire et Solidaire",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["IRLES                     (N)","Epitropica","Equateur",1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["IRLES                     (N)","Comité départemental coopération décentralisé     (CDCD)    ",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["ISSINDOU               (N)","Association Trièves-Palestine","Accueil  étudiant palestinien",3500,"185-02","Coopération culturelle et promotion du français","Assemblée nationale",2011],
["ISSINDOU               (N)","Association \"les Gazelles dauphinoises\"",null,2500,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["ISSINDOU               (N)","Association Tilita-Solidarité",null,1000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["JARDÉ","Ambulances sans frontière",null,5000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["JOSSELIN ","Cités Unies France",null,50000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["KAMMERMANN","Société de bienfaisance de Montevideo        ","Uruguay",3500,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["KAMMERMANN","Projet de création de l'Institut français de Bilbao","Espagne",20000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["KAMMERMANN","Association \"Avenir Positif\" de Pointe-Noire ","Congo",3000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["KAMMERMANN","Lycée français Blaise Pascal de Lubumbashi -","Congo RD",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["KAMMERMANN","Lycée Charles de Gaulle de Concepcion (Chili)","Chili",33000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["KAMMERMANN","Collège franco-argentin de Martinez de Buenos Aires","Argentine",16000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["KAMMERMANN","Lycée français René Descartes de Kinshasa- ","Congo RD",9750,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["KAMMERMANN","Lycée Charlemagne de Pointe-Noire ","Congo",9750,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["KERDRAON            (N)","Armor Goëlo SOLIDARITE TAGHRATE ",null,1500,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["KERT","Droujba Tchernobyl France","Ukraine",6000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["KHIARI","France terre d'asile ",null,20000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["LACHAUD","Electriciens Sans Frontières",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["LAGARDE               (N)","Association aide médicale au Congo","Congo",2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["LAMBLIN                (N)","Comité catholique contre la faim et pour le développement  CCFD",null,2500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["LAMBLIN                (N)","Les Enfants des 1001 collines",null,2500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["LAMOUR                (N)","Vivre à Bossomnoré                 ","Burkina Faso",1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["LAMY","Association \"Colibris d'ici et d'ailleurs\"",null,2300,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["LARCHER","Association des sœurs des saints cœurs                 ","Liban",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["LASBORDES","CAP FQ           COMITE D'ACTION POLITIQUE FRANCO-QUEBECOIS","Canada",7000,"185-02","Coopération culturelle et promotion du français","Assemblée nationale",2011],
["LASBORDES","Eduquamada   ","Madagascar",3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["LAZARO","Association 4 L'ille-Phalempin",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["LAZARO","Les Ptits Lous du Rwanda",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["LAZARO","Les L du désert",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["LEFRAND","Epanouissement                                      ",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["LEPAGE","Ecole Françoise Dolto de Majunga  ","Madagascar",35000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["LEPAGE","Ecole française de Sarrebrück et Dilling        ","Allemagne",25000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["LEPAGE","Fondation de l'école française Erevan Nar-Doss     ","Arménie",20000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["LEPAGE","Foyer résidence pour personnes agées \nSaint Louis des Français - Madrid  ","Espagne",20000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["LEQUILLER","Maison de l'Europe des Yvelines       ",null,5000,"105-02","Action européenne","Assemblée nationale",2011],
["LEVY","CEW France                 COSMETIC EXECUTIVE WOMEN      ASSOC 1901",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MALHERBE            (N)","Les Amis d'Antsirabé","Madagascar",2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MALHERBE            (N)","Vision du Monde               ",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MALLIÉ","Garlaban Togo","Togo",1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MARC","Human Ifrass         PARTICIPER AU 4L TROPHY 2011",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MARIANI                 (N)","Association ACTED    AGENCY FOR TECHNICAL COOPERATION AND DEVELOPMENT                                 ASSOC.    1901",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MARINI","Association AOURAS  «SOCIETE D\u2019ETUDES ET DE RECHERCHES SUR L\u2019AURES ANTIQUE, AOURAS»               ASSOC. 1901",null,5000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["MARINI","Association Terres d'Orient",null,20000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["MARINI","Monastère Saint-Hilarion",null,15000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["MARINI","Monastère Saint-Jacques l'Intercis - MONASTERE ST JACQUES LE MUTILE",null,10000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["MARINI","Centre de recherche sur la Libye antique",null,35000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["MARINI","Association Oise Elblag MALBORK             présidence Marini",null,4000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["MARINI","Ecole biblique de Jérusalem",null,20000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["MARINI","ONG Al Makan Art Association           ONG DE DROIT SYRIEN",null,5000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["MARLAND-MILITELLO (N)","Rotary Club Nice Maeterlinck",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MAUROY","Fondation Jean Jaurès",null,185000,"185-04","Diplomatie culturelle et d'influence - Attractivité et recherche","Assemblée nationale",2011],
["MEHAIGNERIE          (N)","Association Loire-Eaudyssée","Madagascar",10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MONTCHAMP","Fonds Arménien de France",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MORANGE                (N)","Chavalos de Managua",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MORANGE                (N)","AIDASA",null,7000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MOREL-A-L'HUISSIER","Kiwanis Club Mende \"Les Sources\"",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MOREL-A-L'HUISSIER","ALTINE",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MOYNE-BRESSAND  (N)","Les 2 \"Elles\" SandSable",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MUET","Lycée Martin Luther King - Foyer socio-éducatif                          ",null,3000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["MUSELIER","Amicale des Oraniens ",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["MUSELIER","Enfants du Monde                           ASSOC. LOI 1901",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["OGET                      (N)","Association Ede Timoun YO",null,2000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["PANCHER               (N)","Association Réagir : Agir ensemble de Pagny-sur Meuse ",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["PERRUCHOT           (N)","Association d'Aide aux Victimes d'Alhoceima     ","Maroc",2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["PERRUCHOT           (N)","Association Franco-Marocaine                                    ",null,10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["PIRAS                     (N)","Comité de jumelage Arménie      ASSOC LOI 1901","Arménie",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["PLAGNOL","Moldavenir                                              ",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["PONIATOWSKI        (N)","Ebisol                                               ASSOC. LOI 1901",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["PONIATOWSKI        (N)","Action pour Enfants Oubliés d'Eragny-sur Oise",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["POURSINOFF           (N)","Association ACTION MOPTI",null,4000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["POURSINOFF           (N)","Association SANGWA",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["RAIMBOURG           (N)","Association Les Amis de Diawar",null,2000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["REMILLER","APRESS",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["REMILLER","OGEC St Jacques","FRANCE",3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["RENUCCI                 (N)","Association Per a Pace",null,7000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["RICHARD                (N)","Rotary Club Verneuil",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["RICHERT","Association Humanis",null,15000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["ROCHEBLOINE","Association Action Fitiavana",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["ROCHEBLOINE","Association Jeunesse Solide NIKIEMA",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["ROCHEBLOINE","Association Afghanistan-Demain","Afghanistan",3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["ROCHEBLOINE","Association Les enfants Avant Tout",null,26000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["ROCHEBLOINE","Association Da Connexion ",null,8000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["ROCHEBLOINE","Rhône-Arménie Formation echanges","Arménie",10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["ROCHEBLOINE","Radio Arménie","Arménie",5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["ROCHEBLOINE","Solidarité Protestante France-Arménie - SPFA ","Arménie",85500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["ROSSO-DEBORD     (N)","Association CCFD Terre Solidaire    ",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["SAPIN                      (N)             ","Association Réflexe et Partage",null,1000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2011],
["SCHNEIDER              (N)","Melting Pot development","Cameroun",7000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["SORDI                      (N)","Kraing Speu - L'eau, un enjeu vital","Cambodge",3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["SUDARSKIS             (N)","INTA",null,10000,"185-04","Diplomatie culturelle et d'influence - Attractivité et recherche","Assemblée nationale",2011],
["TABAROT","Amphore International","Quatre pays",1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["TABAROT","Association Action Enfance Cambodge ","Cambodge",1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["TABAROT","Terre d'Azur",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["TERROT","CAPDA",null,12000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["TERROT","Amis Luala","RD Congo",3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["TEULADE               (N)","L'école de la vie de Madagascar   ENFANTS DES RUES","Madagascar",1000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["TIBERI                    (N)","Association les œuvres hospitalières françaises de l'ordre de Malte",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["TIBERI                    (N)","Comité Tiers-Monde Sourd",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["VAMPA","Association Mouvement Rural de la Jeunesse Chrétienne (MRJC)",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["VAMPA","Association Normande du Geste pour l'Education (l'ANGE)",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["VANNSON              (N)","Délégation départementale des Vosges de l'association AGIRabcd",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["VANNSON              (N)","Les Amis de Yorola Solidarité entre la France et le Mali","Mali",5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["VERCHERE             (N)","Compagnons du Burkina","Burkina Faso",5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["VIAL                       (N)","Institut français du Proche-Orient (IFPO)",null,10000,"209-02","Développement - Coopération bilatérale","Sénat",2011],
["VIAL                       (N)","Mission archéologique Ras Shamra Ougarit",null,5000,"209-02","Développement - Coopération bilatérale","Sénat",2011],
["VIAL                       (N)","Société d'études syriaques",null,5000,"209-02","Développement - Coopération bilatérale","Sénat",2011],
["WARSMANN","Burkin'Ardenn'Avenir","Burkina Faso",1200,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["WARSMANN","Les Enfants d'Allada  ",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2011],
["YUNG","Alliance française du Brésil ","Brésil",5000,"185-02","Coopération culturelle et promotion du français","Sénat",2011],
["YUNG","Ecole Anne de Kiev   ","Ukraine",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["YUNG","Ecole française de Karikal       ","Inde",5000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2011],
["YUNG","Clinique de Gamkalley à Niamey (NIGER) -           ","Niger",15000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["YUNG","Acid Survivors Foundation - Islamabad    ","Pakistan",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["YUNG","Association \"Enfants français de Madagascar\"  ","Madagascar",15000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["YUNG","Centre de formation Sabatisso de Bamako    ","Mali",12000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["YUNG","Lycée Jean Giono de Turin    ","Italie",5000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2011],
["ACCOYER","Lycée franco-japonais de takinogawa","Japon",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Assemblée nationale",2012],
["ACCOYER","Echanges Sahel",null,10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["AESCHLIMANN","Rotary Club d'Asnières",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["AUBERT","AGIR ABCD pour la Mauritanie",null,10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["AURILLAC","Les Amis de bassiata",null,4000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["AURILLAC","Les mains ouvertes",null,25000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["BAGUET","Les Amis d'Egypte",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["BAYLET","L'association San Filippo Sud",null,3000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["BEL","Citées Unies",null,20000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["BEL","Institut Français du Proche Orient",null,20000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["BEL","Action contre la faim",null,50000,"209-02","Développement - Coopération bilatérale","Sénat",2012],
["BEL","Bibliothèque sans frontière",null,50000,"209-02","Développement - Coopération bilatérale","Sénat",2012],
["BEL","Care France",null,50000,"209-02","Développement - Coopération bilatérale","Sénat",2012],
["BEL","Forum mondial de la langue française","canada",20000,"209-02","Développement - Coopération bilatérale","Sénat",2012],
["BESSE","Association Solidarité vendée-Sénégal",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["BIGNON","Les experts du désert",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["BILLOUT","Initiatives France/Hongrie",null,15000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["BLUM","Horizon Arménie",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["BODIN","Chirurgie solidaire CS",null,5000,"209-08","Développement - Support","Assemblée nationale",2012],
["BOTREL","Tregor solidarité Niger",null,5000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["BRANGET","4L Trophy",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["BRARD","Association française d'appui au développement de la Région du Kayes (AFAK)",null,91000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["BRUNEL","ARCADES",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["CAHUZAC","ATEFAT Haïti",null,1000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["CANTEGRIT","Ecole Jules Verne à Helsinki","Finlande",7000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CANTEGRIT","Lycée français St-Louis de Stockholm","Suède",7000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CANTEGRIT","Lycée Maurice Delafosse Abidjan","Cote d'Ivoire",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CANTEGRIT","Ecole française de Natal Rio de Janeiro","Brésil",5000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CANTEGRIT","Associationdes Ecoles à programme bilingues - FIPA Miami","Etats-Unis",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CANTEGRIT","Nouvelle école française à Cascais","Portugal",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CANTEGRIT","Sté bienfaisance du 14 juillet Sao Paulo","Brésil",5000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["CANTEGRIT","Fondation d'Entraide des Français en Argentine","Argentine",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["CANTEGRIT","Association Française de Solidarité de Munich, ASAIPA/BAYERNE","Allemagne",5000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["CANTEGRIT","Association d'Entraide Médicale des Français du Cameroun - AEMFC","Cameroun",5000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["CANTEGRIT","Club franco-allemand Région Nuremberg","Allemagne",3000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["CANTEGRIT","Union des français de Franconie","Allemagne",3000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["CANTEGRIT","Alliance Française de Vancouver","canada",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["CARAYON","Association Les Enfants de Tanamaza",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["CARREZ","Diverses associations",null,2500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["CHEVENEMENT","Fondation res Publica",null,40000,"185-04","Diplomatie culturelle et d'influence - Attractivité et recherche","Assemblée nationale",2012],
["CHEVENEMENT","Association France-Algérie",null,10000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["CHRIST","Comité Catholique Contre la Faim et pour le Développement",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["CINIERI","Guadeloupe42",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["CINIERI","Rotary club de Firminy",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["COINTAT","Alliance française de San José","Costa-Rica",20000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["COINTAT","Alliance française de Vanuatu","Vanuatu",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["COINTAT","Lycée Tamatave","Madagascar",35000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["COINTAT","Association française de bienfaisance du Vanuatu","Vanuatu",14000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["COINTAT","Association cimetières de Fez","Maroc",21000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["COLOT","Solidarité Roumanie",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["CONWAY-MOURET","Alliance française de San José","Costa-Rica",20000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CONWAY-MOURET","Lycée française d'Irlande","Irlande ",20000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CONWAY-MOURET","Lycée Français de Djibouti","Djibouti",12440,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CONWAY-MOURET","Institut de Recherche et d'études Méditérranée Moyen-Orient (IRRéMo)",null,16000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CONWAY-MOURET","EFBA Education Française de la\" Bay Area\"","San Francisco",5000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CONWAY-MOURET","Fondation Voie Lactée :Bouquinerie Aux trois Dumas","Haiti",15905,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CONWAY-MOURET","Bénévoles sans frontières","Maroc",5000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["CONWAY-MOURET","Diverses associations",null,25655,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["COPE","Moldavenir","Moldavie",8000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["COURTIAL","Rotary club de Clermont de l'Oise",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["COUSIN","L'Abeille de la Solidarité",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["COUSIN","Les Amis de la reine de Miséricorde",null,7000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["CROZON","Le triangle humanitaire",null,10000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["CROZON","Solidarité contre le Sida eb Centrafrique",null,2500,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["DAUBRESSE","Alpabet de l'Amour",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DAUBRESSE","Angata - Lambersart",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DAUBRESSE","FASO Sourire",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DAUBRESSE","Haïti 2010",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DAUBRESSE","Lueur d'orient",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DAUBRESSE","Solidarité Partage sans Frontière",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["D'ETTORE","Electriciens sans frontières",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DE RUGY","Association Pédiatres du monde",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DE RUGY","Association Senankunya",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DE LA VERPILLIERE","Eau Soleil",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DEGAUCHY","4L Trophy",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DEGAUCHY","E.F.N.E.S - échange franco-nigérien","Nigéria",1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DEL PICCHIA","Lycée français de Vienne","Autriche",30000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["DEL PICCHIA","Ecole francophone internationale de Varna","Bulgarie",30000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["DEL PICCHIA","Ecole française Paul-Gaugin","Panama",15000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["DEL PICCHIA","Association \"Parlons français Dallas/Fort Worth\"","Etats-Unis",8000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["DEL PICCHIA","Alliance française d'Andorre","Andorre",5000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["DEL PICCHIA","association \"Athena e. V, gérant \"emploi-Allemagne\"","Allemagne",13000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["DEL PICCHIA","Maison de retraite d'Antsirabé","Madagascar",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["DEL PICCHIA","Ecole française Henri Matisse à Moroni","Les Comores",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["DEL PICCHIA","Communauté française du Maroc\"","Maroc",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["DEL PICCHIA","association de bienfaisance de tel-Aviv et sa région, ABTAR","Israël",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["DEMONTES","Actions solidaires de développement",null,6000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["DEMONTES","CIMADE",null,20000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["DESCOEUR","Association Cantal au Cœur de l'Afrique",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DIARD","Amis provençaux de la langue française",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DIARD","Angels Lives",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DIARD","terre des enfants de Madagascar",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DIONIS du SEJOUR","Burkina TH",null,2500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DULAIT","Musée Afrasyab de Samarcande","Ouzbékistan",5000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["DUMOULIN","Association pour le Développement de Ourossogui",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DUMOULIN","Mosaïque Solidaire",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DUMOULIN","Solid'Afrique",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DUPONT","CCFD",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DURAND","Association Burkinasol",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["DUVERNOIS","ADIFLOR",null,95000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["DUVERNOIS","Alliance français de Brisbane reconstruction bibliothèque","Australie",12000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["DUVERNOIS","Institut Français du Royaume-Uni","Royaume-Uni",8000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["DUVERNOIS","Ecole Jules Verne Helsinki","Finlande",5000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["DUVERNOIS","Renforcement du partenariat avec les collèges d'excellence","Chili",8000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["DUVERNOIS","Association FLAM Qingdao","Chine",2000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["ERHEL","Association Solidarité Goëlo-Burkina",null,1500,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["FERRAND A","Association franco-allemende de Ratisbone","Allemagne",3000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["FERRAND A","Alliance Française","Costa-Rica",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["FERRAND A","Lycée Français de Tamatave ","Madagascar",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["FERRAND A","Lycée Denis Diderot de Nairobi","Kenya",15000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["FERRAND A","Alliance française de Canberra","Australie",12000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["FERRAND A","Alliance française de Calgary","Canada",4300,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["FERRAND A","Lycée français de Stockholm","Suède",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["FERRAND A","Lycée français de Hambourg","Allemagne",7000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["FERRAND A","Alliance française de Durban","Afrique du Sud",6000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["FERRAND A","Alliance française de la Havane","Cuba",4700,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["FERRAND A","Ecole française de Bâle","Suisse",3000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["FERRAND A","Institut de Formation en Soins Médicaux d'Alep","Syrie",17000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["FERRAND A","Compagnie Française de Pompiers Volontaires de Lima","Pérou",18000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["FERRAND A","Association des membres de la légion d'honneur","Vénézuela",5000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["FERRAND A","Association FLAM à Karlsruhe","Allemagne",5000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["FERRAND J-M","Ecole d'Olivia",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["FIORASO","Association Fdolma-Enfants Enfants du Tibet",null,1000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["FLORY","Partage Ardèche Sénégal",null,10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["FLORY","C.O.S.I",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["FOLLIOT","Association avec toi sans toit",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["FOUCAUD","Les Amis de Fort-Dauphin",null,5000,"209-02","Développement - Coopération bilatérale","Sénat",2012],
["FOUCAUD","Diverses associations",null,1000,"209-02","Développement - Coopération bilatérale","Sénat",2012],
["FRANCINA","Talam Léman",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["FRASSA","Collège international francophone de Sarajevo","Bosnie\nHerzégovine",17000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["FRASSA","Alliance française de Cali","Colombie",8000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["FRASSA","Alliance française de San José","Costa Rica",15000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["FRASSA","New-York French American School de Harlem","Etats-Unis",7500,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["FRASSA","Ecole PS58 de Brooklyn","Etats-Unis",7500,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["FRASSA","Amicale des Anciens des Lycées et Ets Scolaires de Fès des Anciens de Fès et sa région (ADAFES)",null,11000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["FRASSA","Association pour le devoir de mémoire","Monaco",1000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["FRASSA","Alliance française de Porto","Portugal",15000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["FRASSA","Alliance française d'Asuncion","Paraguay",5000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["FRASSA","Centre culturel de Kanel","Sénégal",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["FRASSA","Ecole française de Berne","Suisse",13000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["FRASSA","Ecole française Arthur Rimbaud","Chypre",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["FRASSA","ecole maternelle du collège Voltaire","Allemagne",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["GARRAUD","ADM-Vietnam",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GARRAUD","AGIR abcd",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GARRIAUD-MAYLAM","Lycée français Victor Hugo Francfort","Allemagne",12000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["GARRIAUD-MAYLAM","Alliance française de Sucre","Bolivie",3000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["GARRIAUD-MAYLAM","Lycée français St Exupéry ouagadougou","Burkina-Fasso",3000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["GARRIAUD-MAYLAM","Société d'entraide des membres de la Légion d'honneur (comité sud/est Espagne)","Espagne",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["GARRIAUD-MAYLAM","Ecole Jules Verne Helsinki","Finlande",8000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["GARRIAUD-MAYLAM","Alliance française d'Ahmedabad","Inde",45300,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["GARRIAUD-MAYLAM","Alliance française de Bombay","inde",3000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["GARRIAUD-MAYLAM","Ecole Montesquieu de Vilnius","Lituanie",4000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["GARRIAUD-MAYLAM","Alliance française d'El Obeid","Soudan",3000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["GARRIAUD-MAYLAM","Dispensaire français de Londres","Gde-Bretagne",8700,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["GARRIAUD-MAYLAM","Association internationale de Santé","Burkina-Fasso",12000,"209-02","Développement - Coopération bilatérale","Sénat",2012],
["GARRIAUD-MAYLAM","Association Haïtienne d'Aide aux Familles Démunies","Haïti",11000,"209-02","Développement - Coopération bilatérale","Sénat",2012],
["GARRIAUD-MAYLAM","Association Sénégalaise pour la protection des Enfants Déficients Mentaux","Sénégal",4000,"209-02","Développement - Coopération bilatérale","Sénat",2012],
["GARRIAUD-MAYLAM","Association \"Les compagnons Bâtisseurs d'Espoir\"",null,3000,"209-02","Développement - Coopération bilatérale","Sénat",2012],
["GAUBERT","Association Armor Mekong - Le Laos",null,5000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["GAYMARD","PI-SOLEIL",null,4000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GERARD","Association des amis des Pierres Blancs",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GERARD","CAP Santé France",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GERARD","Marcq Tiers-Monde",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GISCARD D'ESTAING Louis","Les Anciens at Amis de la Casamance",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GISCARD D'ESTAING Louis","ARCADE Chamalières",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GISCARD D'ESTAING Louis","France BAOBAS",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GISCARD D'ESTAING Valery","Institut pour la Démocratie en europe",null,90000,"105-02","Action européenne","Assemblée nationale",2012],
["GIULIANI","Fondation Robert Schuman",null,90000,"105-02","Action européenne","Assemblée nationale",2012],
["GOT","Association AGIRabcd délégation départementale Aquitaine",null,1300,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["GOUJON","AMAD et Développement",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GOUJON","Assolampe Bolingo",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GOUJON","Un toit Un lit pour des orphelins en Inde du Sud",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GROMMERCH","MACINA",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GROSPERRIN","4LTEAM",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["GROSPERRIN","Arco Iris",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["HAVARD","Emergence Sud",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["HUE","Fondation Gabriel Péri",null,130000,"185-04","Diplomatie culturelle et d'influence - Attractivité et recherche","Assemblée nationale",2012],
["ISSINDOU","Association France-Russie",null,1000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["ISSINDOU","Association EYBENS-VAMA ","Roumanie",2000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["JACOB","Forum Francophone des Affaires",null,25000,"185-02","Coopération culturelle et promotion du français","Assemblée nationale",2012],
["JACOB","4L Brothers 2012",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["JACOB","Les Gazelles de Brie",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["JACOB","L'envol à 4L",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["JACOB","ASEFS","Shangaï",5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["JARDE","Association solidarité Ecologie Afrique madagascar",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["JARDE","Association Caire Cœur ",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["JARDE","ONG Amitié Picardie magagascar",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["JOSSELIN","Cités Unies France",null,40000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["JOUANNO","Amistad",null,10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["JUANICO","Association Comité de Jumelage Ile Sainte-marie",null,5000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["KAMMERMANN","Institution Jeanne d'Arc dakar","Sénégal",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["KAMMERMANN","Association \"l'Ecole à l'hôpital du Centre hospitalier le Dantec\" de Dakar","Sénégal",5000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["KAMMERMANN","Collège Carmel Saint-Joseph Mechref ","Liban",20000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["KAMMERMANN","L'Alliance Française de Conception","Chili",35000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["KAMMERMANN","L'Alliance franco-Mauritanienne de Nouakchott","Mauritanie",20000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["KAMMERMANN","Centre \"ESTEL\" de Dakar","Sénégal",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["KERT","Association Toufat Nakal",null,10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["KHIARI","Alliance française de Managua","Nicaragua",7000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["KHIARI","Plateforme des ONG françaises pour la Palestine",null,16500,"185-01","Diplomatie culturelle et d'influence - Réseau","Sénat",2012],
["KHIARI","France terre d'asile",null,10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["LABRETTE-MENAGER","Le Mans Solidarité Kyabe",null,2500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["LAGARDE","Association Jeune Europe","Europe",2500,"105-02","Action européenne","Assemblée nationale",2012],
["LAGARDE","Solidarité protestante France-Arménie\n(S.P.F.A)",null,68000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["LAGARDE","Ferme France Arrménie",null,32000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["LAMBERT","Association AMADEA Enfance et Développement Madagascar",null,2000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["LASBORDES","Gif Niger",null,2500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["LASBORDES","Solidarité Rurale France Madagascar",null,2500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["LAZARO","AYITIMOUN YO France",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["LAZARO","LICORNE",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["LAZARO","SHAKTI Népal",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["LECONTE","Ecole française d'Erevan","Arménie",20000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["LECONTE","YERKIR Europe",null,20000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["LECONTE","Education Française  Bay Area","Etats-Unis",2000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["LECONTE","Initiatives France/Hongrie",null,10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["LECONTE","Ecole française de Tirana","Albanie",10000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["LECONTE","Fraternité française d'Alicante","Espagne",4000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["LECONTE","Ecole française Marie Brosset Tbilissi","Georgie",8000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["LECONTE","FLAM à Oulan Bator","Mongolie",5000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["LECONTE","HCR éducation enfants déplacés de SOACHA","Colombie",7500,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["LECONTE","Ecole française Docteur René Guillet","Sénégal",12000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["LECONTE","Collège International Marie de France Montréal","Canada",3000,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["LECONTE","Un autre Monde Zagreb ","Croatie",3000,"185-01","Diplomatie culturelle et d'influence - Réseau","Sénat",2012],
["LECONTE","Maison de la Bretagne à Walbrzych","Pologne",3000,"185-01","Diplomatie culturelle et d'influence - Réseau","Sénat",2012],
["LECONTE","Centre Médico Social de Bamako","Mali",7000,"185-01","Diplomatie culturelle et d'influence - Réseau","Sénat",2012],
["LECONTE","Ecole Livia LAMOURE Bamako","Mali",5000,"185-01","Diplomatie culturelle et d'influence - Réseau","Sénat",2012],
["LECONTE","Divers établissements à l'étranger",null,500,"185-05","Diplomatie culturelle et d'influence - AEFE","Sénat",2012],
["LEFRANC","Comité Tiers Monde Isigny-Carentan",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["LEPAGE","Ecole française Saint-Exupéry Kigali","Rwanda",12000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Biblio école française de Kampala","Ouganda",6000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Collège Fodecariah","Allemagne",3500,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Ecole française de Lomé","Togo",7000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Alliance française de Manakara","Madagascar",2500,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Alliance française de Mahajanga","Madagascar",15000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Lycée français rené Cassin Fianatrantsoa","Madagascar",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Alliance Jacmel","Haïti",8000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Lycée franco hellénique E. Delacroix Athènes","Grèce",6000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Alliances Françaises","Colombie",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Ecole française internationale Vancouver","Canada",8000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Alliance française d'Ahmedabad","Inde",5000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Alliance française Vancouver","Canada",8000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Alliance française de Pasadena","Etats-Unis",5000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["LEPAGE","Centre Médical intern. Ouagadougou","Burkina-Fasso",14000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["MACH","Médicale d'Aide au cameroun","Cameroun",2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MALHERBE","A.SC.H.A.S",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MALHERBE","Amicale Gautier",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MALHERBE","Amitié Madagascar ile-de-France (AMIF)",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MALHERBE","Association Danaya",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MALHERBE","MASOVA",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MALHERBE","SALLYFA",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MALLIE","Humantrip",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MANCEL","Association Franco-Turque",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MANCEL","Association Action Développement Alternatif Madagascar",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MANCEL","Soins pour tous (association de soutien au Cambodge","cambodge",10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MARC","Cités Unies ",null,20000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["MARCON","Echarpes velay Roumanie",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MARINI","Association Terre d'Orient",null,20000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["MARINI","Monastère Saint-Jacques l'Intercis","Liban",5000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["MARINI","Mission archéologique française en Libye",null,20000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["MARLEIX","4L Trophy Cantal Auvergne",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MARTIN-LALANDE","NIRINA",null,6000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MARTIN-LALANDE","SOS Paspanga",null,6500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MARTINEZ","Actions pour Ouarack",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MARTINEZ","Afri'Alp Soleil",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MARTINEZ","Developpement Energies Formation",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MARTINEZ","Nos enfants d'ailleurs",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MARTINEZ","Peuples Solidaires",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MARTINEZ","WANA WANA",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MAUROY","Fondation Jean jaurès",null,160000,"185-04","Diplomatie culturelle et d'influence - Attractivité et recherche","Assemblée nationale",2012],
["MEHAIGNERIE","Mahatsinjo Bretagne",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MIQUEL","L'Alliance française de Managua","Nicaragua",7500,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["MORANGE","A Part",null,7000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MOREL-A-L'HUISSIER","Association Bukovine Lozère",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MOREL-A-L'HUISSIER","Association MENDIEGO",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MOREL-A-L'HUISSIER","Electriciens Sans Frontières Délégation Languedoc Roussillon",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MOREL-A-L'HUISSIER","Loz'Africa",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MOREL-A-L'HUISSIER","RACING 4L",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MOREL-A-L'HUISSIER","Un Bus pour le sénégal",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MORIN","Liberté par les Chamelles",null,3500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MUET","Europe direct Lyon",null,3000,"105-02","Action européenne","Assemblée nationale",2012],
["MUSELIER","Amicale des Oraniens",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MUSELIER","Association les enfants d'Asie",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MUSELIER","Enfants du Monde",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["MUSELIER","Les Jardins d'Hophrys",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["NICOLAS","Rotary Club d'Evreux",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["PATERNOTTE","Association des Frères Unis",null,10000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["PAU-LANGEVIN","Association APDH - Haïti",null,8000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["PERRUCHOT","Pour la Forêt vierge (Raoni)",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["PERRUT","Association Construire Accueillir Préserver Chulémo",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["PIRAS","Comité de jumelage Arménie",null,10000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["POIGNANT","Association SSEDCA",null,6000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["PONIATOWSKI","Eragny lecture",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["PONIATOWSKI","Côte de nuits",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["PRIOU","Vahiny-Magagascar",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["REMILLER","AGUA-BLANCA \"Les enfants de Cali\"",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["REMILLER","Fonds arménien de France",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["REMILLER","La Sénégauloise",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["REMILLER","M'BOUR",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["REMILLER","Franco Béninoise d'Echanges",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["REMILLER","Les Amis d'Alexandre Lienard",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["RICHARD","Action solidarité et Développement sans frontières",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["RICHARD","Aéroclub Roger Janin",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["RICHARD","Solidarité et d'Aide au Développement des Femmes en Mauritanie",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["RICHARD","Lumières de Madagascar",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["RICHARD","Sauvez Sagobé Village",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["ROBINET","Un collège Solidaire",null,5000,"209-07","Développement - Coopération communautaire","Assemblée nationale",2012],
["ROCHEBLOINE","Fonds arménien de France",null,20000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["ROCHEBLOINE","Rharous Amitié",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["ROUQUET","Fond Arménien de France",null,40000,"209-05","Développement - Coopération multilatérale","Assemblée nationale",2012],
["SAINT-LEGER","Association Mendiego",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["SAINT-LEGER","Association RACING 4L",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["SORDI","Kraing Speu - L'eau, un enjeu vital",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["SPAGNOU","SCOBA",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["TABAROT","Action Enfance Cambodge",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["TABAROT","Amphore International",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["TABAROT","Terre d'Azur",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["TABAROT","VALESCOT MILOT",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["TAUGOURDEAU","Urgence Afrique",null,4000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["TEISSIER","Horizons Arménie",null,2500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["TEISSIER","Terre d'Arménie",null,1500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["TERROT","Amour Sans Frontière",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["TERROT","Espoir pour un Enfant",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["TEULADE","Deux comités de jumelage - Sakal (Sénégal) et Bad König ",null,1000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["TIBERI","Les œuvres hospitalières françaises de l'Ordre de Malte dite \"Ordre de Malte\" France",null,3000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["TOURAINE","Association Maison de la Francophonie",null,2500,"185-02","Coopération culturelle et promotion du français","Assemblée nationale",2012],
["TRASSY-PAILLOGUES","ANDAO",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["TRASSY-PAILLOGUES","Numama Togo",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["VANNESTE","Via Zogoré",null,5000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["VANNSON","Kiwanis Club de Gérardmer",null,4500,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["VENDEGOU","Association des femmes de KUNIE",null,10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["VENDEGOU","Association des personnes âgées et handicapées de KOUNIE",null,70000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["VERCHERE","Rotary Club de tarare",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["WARSMANN","Burkin' Ardenn' Avenir",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["WARSMANN","Les Enfants d'Allada",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["WAUQUIEZ","Association Léo Technico",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["WAUQUIEZ","EKITINFO",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["WAUQUIEZ","LACIM",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["WAUQUIEZ","Les Amis du Grand Toukou et du Cameroun",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["WOJCIECHOWSKI","Association Santé Zanskar Himalaya",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["WOJCIECHOWSKI","Association Soutien au foyer de l'Espérance de l'Ile aux Nattes",null,2000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012],
["YUNG","CIMADE","Paris",10000,"151-01","Offre d'un service public de qualité aux Français à l'étranger","Sénat",2012],
["YUNG","Alliance française de Tamatave","Madagascar",4000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["YUNG","Alliance française de Sambava","Madagascar",12000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["YUNG","Association Enfants Français de Madagascar","Madagascar",15000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["YUNG","Lycée François St-Exupéry Ouagadougou","Burkina-Fasso",15000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["YUNG","Association Solidarité France-Brésil",null,5000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["YUNG","Centre médico-social de Bamako","Mali",12000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["YUNG","Foyer de Grenelle","Paris",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["YUNG","Lycée Français de Tokyo","Japon",15000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["YUNG","Lycée Français de Pondichéry","Inde",10000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["YUNG","Ecole Livia LAMOURE","Mali",12000,"185-02","Coopération culturelle et promotion du français","Sénat",2012],
["ZIMMERMANN","Les Amis de Gandiol",null,1000,"209-02","Développement - Coopération bilatérale","Assemblée nationale",2012]]
}