var data = {
"at":{"pays":"Autriche","statut":"Membre de l'UE"},
"be":{"pays":"Belgique","statut":"Membre de l'UE"},
"lu":{"pays":"Luxembourg","statut":"Membre de l'UE"},
"dk":{"pays":"Danemark","statut":"Membre de l'UE"},
"fr":{"pays":"France","statut":"Membre de l'UE"},
"fi":{"pays":"Finlande","statut":"Membre de l'UE"},
"de":{"pays":"Allemagne","statut":"Membre de l'UE"},
"gr":{"pays":"Grèce","statut":"Membre de l'UE"},
"it":{"pays":"Italie","statut":"Membre de l'UE"},
"nl":{"pays":"Pays-Bas","statut":"Membre de l'UE"},
"pt":{"pays":"Portugal","statut":"Membre de l'UE"},
"es":{"pays":"Espagne","statut":"Membre de l'UE"},
"se":{"pays":"Suède","statut":"Membre de l'UE"},
"cz":{"pays":"République tchèque","statut":"Membre de l'UE"},
"ee":{"pays":"Estonie","statut":"Membre de l'UE"},
"hu":{"pays":"Hongrie","statut":"Membre de l'UE"},
"lv":{"pays":"Lettonie","statut":"Membre de l'UE"},
"lt":{"pays":"Lituanie","statut":"Membre de l'UE"},
"mt":{"pays":"Malte","statut":"Membre de l'UE"},
"pl":{"pays":"Pologne","statut":"Membre de l'UE"},
"sk":{"pays":"Slovaquie","statut":"Membre de l'UE"},
"si":{"pays":"Slovénie","statut":"Membre de l'UE"},
"no":{"pays":"Norvège","statut":"Non-membre de l'UE"},
"is":{"pays":"Islande","statut":"Non-membre de l'UE"},
"ch":{"pays":"Suisse","statut":"Non-membre de l'UE"},
"li":{"pays":"Liechtenstein ","statut":"Non-membre de l'UE"},
"bg":{"pays":"Bulgarie","statut":"Adhésion prévue en 2014"},
"ro":{"pays":"Roumanie","statut":"Adhésion prévue en 2014"}}