data = {
"dk":{"nom":"Danemark","gaz":0.00,"couleur":"#a6bddb","echanges":1.41,"ide":"0,44 %","texte":""},
"es":{"nom":"Espagne","gaz":0.00,"couleur":"#a6bddb","echanges":2.24,"ide":"0,81 %","texte":"La Russie fournit 14 % de la demande nationale en pétrole et a envoyé 1,5 million de touristes en Espagne en 2013. "},
"ie":{"nom":"Irlande","gaz":0.00,"couleur":"#a6bddb","echanges":0.47,"ide":"0,12 %","texte":""},
"pt":{"nom":"Portugal","gaz":0.00,"couleur":"#a6bddb","echanges":0.61,"ide":"0,07 %","texte":""},
"gb":{"nom":"Royaume-Uni","gaz":0.00,"couleur":"#a6bddb","echanges":1.75,"ide":"0,13 %","texte":"De nombreuses sociétés russes ont choisi d'être cotées en Bourse à Londres. Les oligarques russes pèsent lourd dans le marché immobilier londonien."},
"se":{"nom":"Suède","gaz":0.00,"couleur":"#a6bddb","echanges":3.62,"ide":"na","texte":""},
"be":{"nom":"Belgique","gaz":1.71,"couleur":"#a6bddb","echanges":1.89,"ide":"na","texte":""},
"nl":{"nom":"Pays-Bas","gaz":4.21,"couleur":"#a6bddb","echanges":3.89,"ide":"0,12 %","texte":"La multinationale anglo-néerlandaise Shell a des intérêts importants en Russie, tandis que le géant gazier Gazprom est engagé dans la province de Groningue. "},
"fr":{"nom":"France","gaz":15.16,"couleur":"#74a9cf","echanges":2.05,"ide":"0,22 %","texte":"Moscou a commandé à la France en juin 2011 deux navires porte-hélicoptères Mistral, dont la construction est assurée par l'entreprise DCNS : le <i>Vladivostok</i> et le <i>Sébastopol</i>. Si un embargo sur les livraisons d'armes à la Russie était décrété, la vente serait probablement annulée et mille emplois à Saint-Nazaire seraient concernés. Côté banques, la Société générale est la plus exposée, puisque la Russie est son deuxième marché derrière la France. "},
"ro":{"nom":"Roumanie","gaz":21.12,"couleur":"#74a9cf","echanges":3.48,"ide":"0,13 %","texte":""},
"lu":{"nom":"Luxembourg","gaz":23.72,"couleur":"#74a9cf","echanges":0.54,"ide":"na","texte":""},
"it":{"nom":"Italie","gaz":25.19,"couleur":"#74a9cf","echanges":2.70,"ide":"0,16 %","texte":"Grâce au dynamisme de ses PME, l'Italie est le deuxième exportateur européen vers la Russie (8 milliards d'euros) derrière l'Allemagne. Le groupe pétrolier ENI est coactionnaire du projet de gazoduc South Stream, porté par Gazprom, qui prévoit de fournir du gaz à l'Europe en passant par la mer Noire et en contournant l'Ukraine."},
"hr":{"nom":"Croatie","gaz":27.44,"couleur":"#74a9cf","echanges":6.19,"ide":"0,65 %","texte":""},
"de":{"nom":"Allemagne","gaz":40.08,"couleur":"#3690c0","echanges":3.82,"ide":"0,45 %","texte":"Avec 40 % de sa consommation de gaz provenant de Russie, l'Allemagne fait partie des pays les plus dépendants et constitue l'un des plus gros marchés d'exportation de la Russie. Gazprom envisage de racheter les capacités de stockage de gaz de BASF en Allemagne."},
"hu":{"nom":"Hongrie","gaz":45.10,"couleur":"#3690c0","echanges":5.82,"ide":"na","texte":"La Hongrie de Viktor Orban vient de signer un accord colossal avec la Russie pour l'extension de son parc nucléaire, moyennant 11 milliards d'euros de Moscou."},
"si":{"nom":"Slovénie","gaz":46.66,"couleur":"#3690c0","echanges":3.05,"ide":"0,40 %","texte":""},
"gr":{"nom":"Grèce","gaz":57.08,"couleur":"#0570b0","echanges":8.31,"ide":"na","texte":"Moscou a promis de fournir du gaz à un prix attractif à la Grèce, un engagement alléchant pour un pays dont l'économie est toujours en crise. "},
"pl":{"nom":"Pologne","gaz":58.64,"couleur":"#0570b0","echanges":8.65,"ide":"0,29 %","texte":""},
"at":{"nom":"Autriche","gaz":65.68,"couleur":"#0570b0","echanges":2.90,"ide":"5,25 %","texte":"Les entreprises autrichiennes ont investi environ 7 milliards d'euros en Russie et ont décroché pour près d'1,5 milliard d'euros de contrats à l'occasion des Jeux olympiques de Sotchi. La banque autrichienne Raiffeisen tire par exemple 21 % de ses revenus du marché russe."},
"lv":{"nom":"Lettonie","gaz":74.05,"couleur":"#0570b0","echanges":13.18,"ide":"4,71 %","texte":""},
"bg":{"nom":"Bulgarie","gaz":85.45,"couleur":"#034e7b","echanges":12.73,"ide":"4,41 %","texte":""},
"ee":{"nom":"Estonie","gaz":100.00,"couleur":"#034e7b","echanges":8.33,"ide":"4,64 %","texte":""},
"fi":{"nom":"Finlande","gaz":100.00,"couleur":"#034e7b","echanges":13.88,"ide":"0,80 %","texte":"La Finlande souffre déjà de la chute du rouble, qui affecte ses entreprises du secteur agroalimentaire. En 2013, les exportations finlandaises en Russie se sont rétractées de 6 %."},
"cz":{"nom":"République Tchèque","gaz":100.00,"couleur":"#034e7b","echanges":4.24,"ide":"0,40 %","texte":"Les exportations tchèques vers Moscou ont quadruplé en 2013 par rapport à 2012, le pays ayant fait des efforts pour progresser sur le marché russe, afin de contrebalancer le recul de la zone euro."},
"lt":{"nom":"Lituanie","gaz":100.00,"couleur":"#034e7b","echanges":25.53,"ide":"4,75 %","texte":"La Lituanie a déposé en janvier 2011 une plainte à Bruxelles contre Gazprom, qu'elle accusait d'abus de position dominante. Dans les pays baltes, presque l'intégralité des besoins en gaz sont couverts par la Russie."},
"sk":{"nom":"Slovaquie","gaz":100.00,"couleur":"#034e7b","echanges":6.51,"ide":"na","texte":"La Slovaquie est largement tributaire du gaz (100 %) et du pétrole (80 %) russes. "},
"cy":{"nom":"Chypre","gaz":"na","couleur":"#e0e0e0","echanges":1.09,"ide":"13,78 %","texte":"Chypre est l'une des portes d'accès en Europe des oligarques russes. C'est aussi le pays d'Europe qui investit le plus en Russie, par l'entremise de sociétés à capitaux russes basées sur l'île. Pendant la débâcle financière de mars 2013, le gouvernement avait appelé Moscou à l'aide, sans succès."},
"mt":{"nom":"Malte","gaz":"na","couleur":"#e0e0e0","echanges":"na","ide":"0,11 %","texte":""},
"ru":{"nom":"Russie","gaz":"na","couleur":"#fee0d2","texte":""}
}