var deputes = {
	"aaData":[
	  ["M.","Abad","Damien","Damien Abad","Ain",5,"UMP","contre",1],
	  ["Mme","Abeille","Laurence","Laurence Abeille","Val-de-Marne",6,"ECOLO","pour",1],
	  ["M.","Aboubacar","Ibrahim","Ibrahim Aboubacar","Mayotte",2,"SRC","pour",1],
	  ["M.","Aboud","Elie ","Elie  Aboud","Hérault",6,"UMP","contre",1],
	  ["M.","Accoyer","Bernard","Bernard Accoyer","Haute-Savoie",1,"UMP","contre",1],
	  ["Mme","Adam","Patricia","Patricia Adam","Finistère",2,"SRC","pour",1],
	  ["Mme","Alaux","Sylviane","Sylviane Alaux","Pyrénées-Atlantiques",6,"SRC","pour",1],
	  ["M.","Alauzet","Eric","Eric Alauzet","Doubs",2,"ECOLO","pour",1],
	  ["M.","Albarello","Yves","Yves Albarello","Seine-et-Marne",7,"UMP","contre",1],
	  ["Mme","Allain","Brigitte","Brigitte Allain","Dordogne",2,"ECOLO","pour",1],
	  ["M.","Allossery","Jean-Pierre","Jean-Pierre Allossery","Nord",15,"SRC","pour",1],
	  ["Mme","Ameline","Nicole","Nicole Ameline","Calvados",4,"UMP","abstention",1],
	  ["M.","Amirshahi","Pouria","Pouria Amirshahi","Français de l'étranger",9,"SRC","pour",1],
	  ["M.","André","François","François André","Ille-et-Vilaine",3,"SRC","pour",1],
	  ["Mme","Andrieux","Sylvie","Sylvie Andrieux","Bouches-du-Rhône",3,"SRC","pour",1],
	  ["M.","Apparu","Benoist","Benoist Apparu","Marne",4,"UMP","pour",1],
	  ["Mme","Appéré","Nathalie","Nathalie Appéré","Ille-et-Vilaine",2,"SRC","pour",1],
	  ["M.","Asensi","François","François Asensi","Seine-Saint-Denis",11,"GDR","pour",1],
	  ["M.","Assaf","Christian","Christian Assaf","Hérault",8,"SRC","pour",1],
	  ["M.","Assouly","Avi ","Avi  Assouly","Bouches-du-Rhône",5,"SRC","pour",1],
	  ["Mme","Attard","Isabelle","Isabelle Attard","Calvados",5,"ECOLO","pour",1],
	  ["M.","Aubert","Julien","Julien Aubert","Vaucluse",5,"UMP","contre",1],
	  ["M.","Audibert-Troin","Olivier","Olivier Audibert-Troin","Var",8,"UMP","contre",1],
	  ["Mme","Auroi","Danielle","Danielle Auroi","Puy-de-Dôme",3,"ECOLO","pour",1],
	  ["M.","Aylagas","Pierre","Pierre Aylagas","Pyrénées-Orientales",4,"SRC","pour",1],
	  ["M.","Azérot","Bruno Nestor","Bruno Nestor Azérot","Martinique",2,"GDR","contre",1],
	  ["M.","Bachelay","Alexis","Alexis Bachelay","Hauts-de-Seine",1,"SRC","pour",1],
	  ["M.","Bachelay","Guillaume","Guillaume Bachelay","Seine-Maritime",4,"SRC","pour",1],
	  ["M.","Bacquet","Jean-Paul","Jean-Paul Bacquet","Puy-de-Dôme",4,"SRC","pour",1],
	  ["M.","Baert","Dominique","Dominique Baert","Nord",8,"SRC","pour",1],
	  ["M.","Balkany","Patrick","Patrick Balkany","Hauts-de-Seine",5,"UMP","contre",1],
	  ["M.","Bapt","Gérard","Gérard Bapt","Haute-Garonne",2,"SRC","pour",1],
	  ["M.","Barbier","Jean-Pierre","Jean-Pierre Barbier","Isère",7,"UMP","contre",1],
	  ["M.","Barbier","Frédéric ","Frédéric  Barbier","Doubs",4,"SRC","pour",1],
	  ["M.","Bardy","Serge","Serge Bardy","Maine-et-Loire",6,"SRC","pour",1],
	  ["Mme","Bareigts","Ericka","Ericka Bareigts","La Réunion",1,"SRC","pour",1],
	  ["M.","Baroin","François","François Baroin","Aube",3,"UMP","contre",1],
	  ["M.","Bartolone","Claude","Claude Bartolone","Seine-Saint-Denis",9,"SRC","non-votant",1],
	  ["M.","Bataille","Christian","Christian Bataille","Nord",12,"SRC","pour",1],
	  ["Mme","Battistel","Marie-Noëlle","Marie-Noëlle Battistel","Isère",4,"SRC","pour",1],
	  ["M.","Baumel","Laurent","Laurent Baumel","Indre-et-Loire",4,"SRC","pour",1],
	  ["M.","Baumel","Philippe","Philippe Baumel","Saône-et-Loire",3,"SRC","pour",1],
	  ["M.","Baupin","Denis","Denis Baupin","Paris",10,"ECOLO","pour",1],
	  ["M.","Bays","Nicolas","Nicolas Bays","Pas-de-Calais",12,"SRC","pour",1],
	  ["Mme","Beaubatie","Catherine","Catherine Beaubatie","Haute-Vienne",3,"SRC","pour",1],
	  ["Mme","Bechtel","Marie-Françoise","Marie-Françoise Bechtel","Aisne",4,"SRC","abstention",1],
	  ["M.","Beffara","Jean-Marie","Jean-Marie Beffara","Indre-et-Loire",3,"SRC","pour",1],
	  ["Mme","Bello","Huguette","Huguette Bello","La Réunion",2,"GDR","-",1],
	  ["M.","Belot","Luc","Luc Belot","Maine-et-Loire",1,"SRC","pour",1],
	  ["M.","Bénisti","Jacques-Alain","Jacques-Alain Bénisti","Val-de-Marne",4,"UMP","contre",1],
	  ["M.","Benoit","Thierry","Thierry Benoit","Ille-et-Vilaine",6,"UDI","contre",1],
	  ["Mme","Berger","Karine","Karine Berger","Hautes-Alpes",1,"SRC","pour",1],
	  ["M.","Berrios","Sylvain ","Sylvain  Berrios","Val-de-Marne",1,"UMP","contre",1],
	  ["Mme","Berthelot","Chantal","Chantal Berthelot","Guyane",2,"SRC","pour",1],
	  ["M.","Bertrand","Xavier","Xavier Bertrand","Aisne",2,"UMP","contre",1],
	  ["Mme","Besse","Véronique","Véronique Besse","Vendée",4,"NI","contre",1],
	  ["Mme","Biémouret","Gisèle","Gisèle Biémouret","Gers",2,"SRC","pour",1],
	  ["M.","Bies","Philippe","Philippe Bies","Bas-Rhin",2,"SRC","pour",1],
	  ["M.","Binet","Erwann","Erwann Binet","Isère",8,"SRC","pour",1],
	  ["M.","Blanc","Etienne","Etienne Blanc","Ain",3,"UMP","contre",1],
	  ["M.","Blazy","Jean-Pierre","Jean-Pierre Blazy","Val-d'Oise",9,"SRC","pour",1],
	  ["M.","Blein","Yves","Yves Blein","Rhône",14,"SRC","pour",1],
	  ["M.","Bleunven","Jean-Luc","Jean-Luc Bleunven","Finistère",3,"SRC","pour",1],
	  ["M.","Bloche","Patrick","Patrick Bloche","Paris",7,"SRC","pour",1],
	  ["M.","Bocquet","Alain","Alain Bocquet","Nord",20,"GDR","pour",1],
	  ["M.","Boisserie","Daniel","Daniel Boisserie","Haute-Vienne",2,"SRC","pour",1],
	  ["Mme","Boistard","Pascale","Pascale Boistard","Somme",1,"SRC","pour",1],
	  ["M.","Bompard","Jacques","Jacques Bompard","Vaucluse",4,"NI","contre",1],
	  ["Mme","Bonneton","Michele","Michele Bonneton","Isère",9,"ECOLO","pour",1],
	  ["M.","Bonnot","Marcel","Marcel Bonnot","Doubs",3,"UMP","contre",1],
	  ["M.","Borgel","Christophe","Christophe Borgel","Haute-Garonne",9,"SRC","pour",1],
	  ["M.","Borloo","Jean-Louis","Jean-Louis Borloo","Nord",21,"UDI","pour",1],
	  ["M.","Bouchet","Jean-Claude","Jean-Claude Bouchet","Vaucluse",2,"UMP","contre",1],
	  ["M.","Boudié","Florent","Florent Boudié","Gironde",10,"SRC","pour",1],
	  ["Mme","Bouillé","Marie-Odile","Marie-Odile Bouillé","Loire-Atlantique",8,"SRC","pour",1],
	  ["M.","Bouillon","Christophe","Christophe Bouillon","Seine-Maritime",5,"SRC","pour",1],
	  ["M.","Bourdouleix","Gilles","Gilles Bourdouleix","Maine-et-Loire",5,"UDI","contre",1],
	  ["Mme","Bourguignon","Brigitte","Brigitte Bourguignon","Pas-de-Calais",6,"SRC","pour",1],
	  ["M.","Boutih","Malek","Malek Boutih","Essonne",10,"SRC","pour",1],
	  ["Mme","Bouziane-Laroussi","Kheira","Kheira Bouziane-Laroussi","Côte-d'Or",3,"SRC","pour",1],
	  ["Mme","Boyer","Valérie","Valérie Boyer","Bouches-du-Rhône",1,"UMP","contre",1],
	  ["M.","Braillard","Thierry","Thierry Braillard","Rhône",1,"RRDP","pour",1],
	  ["M.","Bréhier","Emeric","Emeric Bréhier","Seine-et-Marne",10,"SRC","pour",1],
	  ["M.","Breton","Xavier","Xavier Breton","Ain",1,"UMP","contre",1],
	  ["M.","Briand","Philippe","Philippe Briand","Indre-et-Loire",5,"UMP","contre",1],
	  ["M.","Bricout","Jean-Louis","Jean-Louis Bricout","Aisne",3,"SRC","pour",1],
	  ["M.","Bridey","Jean-Jacques","Jean-Jacques Bridey","Val-de-Marne",7,"SRC","pour",1],
	  ["M.","Brochand","Bernard","Bernard Brochand","Alpes-Maritimes",8,"UMP","contre",1],
	  ["M.","Brottes","François","François Brottes","Isère",5,"SRC","pour",1],
	  ["Mme","Bruneau","Isabelle","Isabelle Bruneau","Indre",2,"SRC","pour",1],
	  ["Mme","Buffet","Marie-George","Marie-George Buffet","Seine-Saint-Denis",4,"GDR","pour",1],
	  ["M","Bui","Gwengan","Gwengan Bui","Finistère",4,"SRC","pour",1],
	  ["Mme","Buis","Sabine","Sabine Buis","Ardèche",3,"SRC","pour",1],
	  ["M.","Buisine","Jean-Claude","Jean-Claude Buisine","Somme",3,"SRC","pour",1],
	  ["Mme","Bulteau","Sylviane","Sylviane Bulteau","Vendée",2,"SRC","pour",1],
	  ["M.","Burroni","Vincent","Vincent Burroni","Bouches-du-Rhône",12,"SRC","pour",1],
	  ["M.","Bussereau","Dominique","Dominique Bussereau","Charente-Maritime",4,"UMP","contre",1],
	  ["M.","Calmette","Alain","Alain Calmette","Cantal",1,"SRC","pour",1],
	  ["M.","Cambadélis","Jean-Christophe","Jean-Christophe Cambadélis","Paris",16,"SRC","pour",1],
	  ["M.","Candelier","Jean-Jacques","Jean-Jacques Candelier","Nord",16,"GDR","pour",1],
	  ["Mme","Capdevielle","Colette","Colette Capdevielle","Pyrénées-Atlantiques",5,"SRC","pour",1],
	  ["M.","Capet","Yann","Yann Capet","Pas-de-Calais",7,"SRC","pour",1],
	  ["M.","Caresche","Christophe","Christophe Caresche","Paris",18,"SRC","pour",1],
	  ["M.","Carpentier","Jean-Noël","Jean-Noël Carpentier","Val-d'Oise",3,"RRDP","pour",1],
	  ["M.","Carré","Olivier","Olivier Carré","Loiret",1,"UMP","contre",1],
	  ["Mme","Carrey-Conte","Fanelie","Fanelie Carrey-Conte","Paris",15,"SRC","pour",1],
	  ["M.","Carrez","Gilles","Gilles Carrez","Val-de-Marne",5,"UMP","contre",1],
	  ["Mme","Carrillon-Couvreur","Martine","Martine Carrillon-Couvreur","Nièvre",1,"SRC","pour",1],
	  ["M.","Carvalho","Patrice","Patrice Carvalho","Oise",6,"GDR","contre",1],
	  ["M.","Castaner","Christophe","Christophe Castaner","Alpes-de-Haute-Provence",2,"SRC","pour",1],
	  ["M.","Cathala","Laurent","Laurent Cathala","Val-de-Marne",2,"SRC","pour",1],
	  ["M.","Caullet","Jean-Yves","Jean-Yves Caullet","Yonne",2,"SRC","pour",1],
	  ["M.","Cavard","Christophe","Christophe Cavard","Gard",6,"ECOLO","pour",1],
	  ["M.","Censi","Yves","Yves Censi","Aveyron",1,"UMP","contre",1],
	  ["Mme","Chabanne","Nathalie","Nathalie Chabanne","Pyrénées-Atlantiques",2,"SRC","pour",1],
	  ["M.","Chalus","Ary","Ary Chalus","Guadeloupe",3,"RRDP","contre",1],
	  ["M.","Chambefort","Guy","Guy Chambefort","Allier",1,"SRC","pour",1],
	  ["M.","Chanteguet","Jean-Paul","Jean-Paul Chanteguet","Indre",1,"SRC","pour",1],
	  ["Mme","Chapdelaine","Marie-Anne","Marie-Anne Chapdelaine","Ille-et-Vilaine",1,"SRC","pour",1],
	  ["M.","Charasse","Gérard","Gérard Charasse","Allier",3,"RRDP","-",1],
	  ["M.","Charroux","Gaby","Gaby Charroux","Bouches-du-Rhône",13,"GDR","pour",1],
	  ["M.","Chartier","Jérôme","Jérôme Chartier","Val-d'Oise",7,"UMP","contre",1],
	  ["M.","Chassaigne","André","André Chassaigne","Puy-de-Dôme",5,"GDR","pour",1],
	  ["M.","Chatel","Luc","Luc Chatel","Haute-Marne",1,"UMP","contre",1],
	  ["M.","Chauveau","Guy-Michel","Guy-Michel Chauveau","Sarthe",3,"SRC","pour",1],
	  ["Mme","Chauvel","Dominique","Dominique Chauvel","Seine-Maritime",10,"SRC","pour",1],
	  ["M.","Cherki","Pascal","Pascal Cherki","Paris",11,"SRC","pour",1],
	  ["M.","Cherpion","Gérard","Gérard Cherpion","Vosges",2,"UMP","contre",1],
	  ["M.","Chevrollier","Guillaume","Guillaume Chevrollier","Mayenne",2,"UMP","contre",1],
	  ["M.","Chrétien","Alain","Alain Chrétien","Haute-Saône",1,"UMP","contre",1],
	  ["M.","Christ","Jean-Louis","Jean-Louis Christ","Haut-Rhin",2,"UMP","contre",1],
	  ["M.","Cinieri","Dino","Dino Cinieri","Loire",4,"UMP","contre",1],
	  ["M.","Ciot","Jean-David","Jean-David Ciot","Bouches-du-Rhône",14,"SRC","pour",1],
	  ["M.","Ciotti","Eric","Eric Ciotti","Alpes-Maritimes",1,"UMP","contre",1],
	  ["M.","Claeys","Alain","Alain Claeys","Vienne",1,"SRC","pour",1],
	  ["M.","Clément","Jean-Michel","Jean-Michel Clément","Vienne",3,"SRC","pour",1],
	  ["Mme","Clergeau","Marie-Françoise","Marie-Françoise Clergeau","Loire-Atlantique",2,"SRC","pour",1],
	  ["M.","Cochet","Philippe","Philippe Cochet","Rhône",5,"UMP","contre",1],
	  ["M.","Collard","Gilbert","Gilbert Collard","Gard",2,"NI","contre",1],
	  ["M.","Copé","Jean-François","Jean-François Copé","Seine-et-Marne",6,"UMP","contre",1],
	  ["M.","Cordery","Philip","Philip Cordery","Français de l'étranger",4,"SRC","pour",1],
	  ["M.","Cornut-Gentille","François","François Cornut-Gentille","Haute-Marne",2,"UMP","contre",1],
	  ["M.","Coronado","Sergio","Sergio Coronado","Français de l'étranger",2,"ECOLO","pour",1],
	  ["Mme","Corre","Valérie","Valérie Corre","Loiret",6,"SRC","pour",1],
	  ["M.","Cottel","Jean-Jacques","Jean-Jacques Cottel","Pas-de-Calais",1,"SRC","pour",1],
	  ["M.","Courtial","Edouard","Edouard Courtial","Oise",7,"UMP","contre",1],
	  ["Mme","Coutelle","Catherine","Catherine Coutelle","Vienne",2,"SRC","pour",1],
	  ["M.","Couve","Jean-Michel","Jean-Michel Couve","Var",4,"UMP","contre",1],
	  ["M.","Cresta","Jacques","Jacques Cresta","Pyrénées-Orientales",1,"SRC","pour",1],
	  ["Mme","Crozon","Pascale","Pascale Crozon","Rhône",6,"SRC","pour",1],
	  ["M.","Da Silva","Carlos","Carlos Da Silva","Essonne",1,"SRC","pour",1],
	  ["Mme","Dagoma","Seybah","Seybah Dagoma","Paris",5,"SRC","pour",1],
	  ["Mme","Dalloz","Marie-Christine","Marie-Christine Dalloz","Jura",2,"UMP","contre",1],
	  ["M.","Daniel","Yves","Yves Daniel","Loire-Atlantique",6,"SRC","pour",1],
	  ["M.","Darmanin","Gérald","Gérald Darmanin","Nord",10,"UMP","contre",1],
	  ["M.","Dassault","Olivier","Olivier Dassault","Oise",1,"UMP","contre",1],
	  ["M.","Daubresse","Marc-Philippe","Marc-Philippe Daubresse","Nord",4,"UMP","contre",1],
	  ["M.","de Courson","Charles","Charles de Courson","Marne",5,"UDI","contre",1],
	  ["M.","de Ganay","Claude","Claude de Ganay","Loiret",3,"UMP","contre",1],
	  ["Mme","de La Raudière","Laure","Laure de La Raudière","Eure-et-Loir",3,"UMP","contre",1],
	  ["M.","de La Verpillière","Charles","Charles de La Verpillière","Ain",2,"UMP","contre",1],
	  ["M.","de Mazières","François","François de Mazières","Yvelines",1,"UMP","contre",1],
	  ["M.","de Rocca Serra","Camille","Camille de Rocca Serra","Corse-du-Sud",2,"UMP","contre",1],
	  ["M.","De Rugy","François","François De Rugy","Loire-Atlantique",1,"ECOLO","pour",1],
	  ["M.","Debré","Bernard","Bernard Debré","Paris",4,"UMP","contre",1],
	  ["M.","Decool","Jean-Pierre","Jean-Pierre Decool","Nord",14,"UMP","contre",1],
	  ["M.","Deflesselles","Bernard","Bernard Deflesselles","Bouches-du-Rhône",9,"UMP","contre",1],
	  ["M.","Degauchy","Lucien","Lucien Degauchy","Oise",5,"UMP","contre",1],
	  ["M.","Deguilhem","Pascal","Pascal Deguilhem","Dordogne",1,"SRC","pour",1],
	  ["M.","Delatte","Rémi","Rémi Delatte","Côte-d'Or",2,"UMP","contre",1],
	  ["Mme","Delaunay","Florence","Florence Delaunay","Landes",1,"SRC","pour",1],
	  ["M.","Delcourt","Guy","Guy Delcourt","Pas-de-Calais",3,"SRC","pour",1],
	  ["Mme","Delga","Carole","Carole Delga","Haute-Garonne",8,"SRC","pour",1],
	  ["M.","Demilly","Stéphane","Stéphane Demilly","Somme",5,"UDI","contre",1],
	  ["M.","Denaja","Sébastien","Sébastien Denaja","Hérault",7,"SRC","pour",1],
	  ["Mme","Descamps-Crosnier","Françoise","Françoise Descamps-Crosnier","Yvelines",8,"SRC","pour",1],
	  ["Mme","Dessus","Sophie","Sophie Dessus","Corrèze",1,"SRC","pour",1],
	  ["M.","Destans","Jean-Louis","Jean-Louis Destans","Eure",2,"SRC","pour",1],
	  ["M.","Destot","Michel","Michel Destot","Isère",3,"SRC","pour",1],
	  ["M.","Devedjian","Patrick","Patrick Devedjian","Hauts-de-Seine",13,"UMP","contre",1],
	  ["M.","Dhuicq","Nicolas","Nicolas Dhuicq","Aube",1,"UMP","contre",1],
	  ["Mme","Dion","Sophie","Sophie Dion","Haute-Savoie",6,"UMP","contre",1],
	  ["M.","Dolez","Marc","Marc Dolez","Nord",17,"GDR","pour",1],
	  ["Mme","Dombre-Coste","Fanny","Fanny Dombre-Coste","Hérault",3,"SRC","pour",1],
	  ["M.","Door","Jean-Pierre","Jean-Pierre Door","Loiret",4,"UMP","contre",1],
	  ["M.","Dord","Dominique","Dominique Dord","Savoie",1,"UMP","contre",1],
	  ["M.","Dosière","René","René Dosière","Aisne",1,"SRC","pour",1],
	  ["Mme","Doucet","Sandrine","Sandrine Doucet","Gironde",1,"SRC","pour",1],
	  ["M.","Doucet","Philippe","Philippe Doucet","Val-d'Oise",5,"SRC","pour",1],
	  ["M.","Douillet","David","David Douillet","Yvelines",12,"UMP","contre",1],
	  ["M","Drapeau","Jean-Luc","Jean-Luc Drapeau","Deux-Sèvres",2,"SRC","pour",1],
	  ["Mme","Dubié","Jeanine","Jeanine Dubié","Hautes-Pyrénées",2,"RRDP","pour",1],
	  ["Mme","Dubois","Françoise","Françoise Dubois","Sarthe",1,"UMP","contre",1],
	  ["Mme","Dubois","Marianne","Marianne Dubois","Loiret",5,"SRC","pour",1],
	  ["Mme","Duby-Muller","Virginie","Virginie Duby-Muller","Haute-Savoie",4,"UMP","contre",1],
	  ["M.","Dufau","Jean-Pierre","Jean-Pierre Dufau","Landes",2,"SRC","pour",1],
	  ["Mme","Dufour-Tonini","Anne-Lise","Anne-Lise Dufour-Tonini","Nord",19,"SRC","pour",1],
	  ["Mme","Dumas","Françoise","Françoise Dumas","Gard",1,"SRC","pour",1],
	  ["M.","Dumas","William","William Dumas","Gard",5,"SRC","pour",1],
	  ["Mme","Dumont","Laurence","Laurence Dumont","Calvados",2,"SRC","pour",1],
	  ["M.","Dumont","Jean-Louis","Jean-Louis Dumont","Meuse",2,"SRC","pour",1],
	  ["M.","Dupont-Aignan","Nicolas","Nicolas Dupont-Aignan","Essonne",8,"NI","contre",1],
	  ["M.","Dupré","Jean-Paul","Jean-Paul Dupré","Aude",3,"SRC","pour",1],
	  ["M.","Durand","Yves","Yves Durand","Nord",11,"SRC","pour",1],
	  ["M.","Duron","Philippe","Philippe Duron","Calvados",1,"SRC","pour",1],
	  ["M.","Dussopt","Olivier","Olivier Dussopt","Ardèche",2,"SRC","pour",1],
	  ["M.","Eckert","Christian","Christian Eckert","Meurthe-et-Moselle",3,"SRC","pour",1],
	  ["M.","Emmanuelli","Henri","Henri Emmanuelli","Landes",3,"SRC","pour",1],
	  ["Mme","Erhel","Corinne","Corinne Erhel","Côtes-d'Armor",5,"SRC","pour",1],
	  ["Mme","Errante","Sophie","Sophie Errante","Loire-Atlantique",10,"SRC","pour",1],
	  ["M.","Estrosi","Christian","Christian Estrosi","Alpes-Maritimes",5,"UMP","contre",1],
	  ["Mme","Fabre","Marie-Hélène","Marie-Hélène Fabre","Aude",2,"SRC","pour",1],
	  ["M.","Falorni","Olivier","Olivier Falorni","Charente-Maritime",1,"RRDP","pour",1],
	  ["M.","Fasquelle","Daniel","Daniel Fasquelle","Pas-de-Calais",4,"UMP","contre",1],
	  ["Mme","Faure","Martine","Martine Faure","Gironde",12,"SRC","pour",1],
	  ["M.","Faure","Olivier","Olivier Faure","Seine-et-Marne",11,"SRC","pour",1],
	  ["M.","Fauré","Alain","Alain Fauré","Ariège",2,"SRC","pour",1],
	  ["M.","Favennec","Yannick","Yannick Favennec","Mayenne",3,"UDI","contre",1],
	  ["M.","Fekl","Matthias","Matthias Fekl","Lot-et-Garonne",2,"SRC","pour",1],
	  ["M","Feltesse","Vincent","Vincent Feltesse","Gironde",2,"SRC","pour",1],
	  ["M.","Fenech","Georges","Georges Fenech","Rhône",11,"UMP","contre",1],
	  ["M.","Féron","Hervé","Hervé Féron","Meurthe-et-Moselle",2,"SRC","pour",1],
	  ["M.","Ferrand","Richard","Richard Ferrand","Finistère",6,"SRC","pour",1],
	  ["M.","Fillon","François","François Fillon","Paris",2,"UMP","contre",1],
	  ["M.","Folliot","Philippe","Philippe Folliot","Tarn",1,"UDI","contre",1],
	  ["Mme","Fort","Marie-Louise","Marie-Louise Fort","Yonne",3,"UMP","contre",1],
	  ["M.","Fougerat","Jean-Pierre","Jean-Pierre Fougerat","Loire-Atlantique",3,"SRC","pour",1],
	  ["M.","Foulon","Yves","Yves Foulon","Gironde",8,"UMP","contre",1],
	  ["M.","Fourage","Hugues","Hugues Fourage","Vendée",5,"SRC","pour",1],
	  ["Mme","Fournier-Armand","Michele","Michele Fournier-Armand","Vaucluse",1,"SRC","pour",1],
	  ["M.","Françaix","Michel","Michel Françaix","Oise",3,"SRC","pour",1],
	  ["M.","Francina","Marc","Marc Francina","Haute-Savoie",5,"UMP","-",1],
	  ["M.","Franqueville","Christian","Christian Franqueville","Vosges",4,"SRC","pour",1],
	  ["Mme","Fraysse","Jacqueline","Jacqueline Fraysse","Hauts-de-Seine",4,"GDR","pour",1],
	  ["M.","Fritch","Edouard","Edouard Fritch","Polynésie Française",1,"UDI","contre",1],
	  ["M.","Fromantin","Jean-Christophe","Jean-Christophe Fromantin","Hauts-de-Seine",6,"UDI","contre",1],
	  ["M.","Fromion","Yves","Yves Fromion","Cher",1,"UMP","contre",1],
	  ["M.","Fruteau","Jean-Claude","Jean-Claude Fruteau","La Réunion",5,"SRC","pour",1],
	  ["M.","Furst","Laurent","Laurent Furst","Bas-Rhin",6,"UMP","contre",1],
	  ["M.","Gagnaire","Jean-Louis","Jean-Louis Gagnaire","Loire",2,"SRC","pour",1],
	  ["Mme","Gaillard","Geneviève","Geneviève Gaillard","Deux-Sèvres",1,"SRC","pour",1],
	  ["M.","Galut","Yann","Yann Galut","Cher",3,"SRC","pour",1],
	  ["M.","Gandolfi-Scheit","Sauveur","Sauveur Gandolfi-Scheit","Haute-Corse",1,"UMP","contre",1],
	  ["M.","Gaymard","Hervé","Hervé Gaymard","Savoie",2,"UMP","contre",1],
	  ["Mme","Genevard","Annie","Annie Genevard","Doubs",5,"UMP","contre",1],
	  ["M.","Geoffroy","Guy","Guy Geoffroy","Seine-et-Marne",9,"UMP","contre",1],
	  ["Mme","Geoffroy","Hélène","Hélène Geoffroy","Rhône",7,"SRC","pour",1],
	  ["M.","Gérard","Bernard","Bernard Gérard","Nord",9,"UMP","contre",1],
	  ["M.","Germain","Jean-Marc","Jean-Marc Germain","Hauts-de-Seine",12,"SRC","pour",1],
	  ["M.","Gest","Alain","Alain Gest","Somme",4,"UMP","contre",1],
	  ["M.","Giacobbi","Paul","Paul Giacobbi","Haute-Corse",2,"RRDP","pour",1],
	  ["M.","Gibbes","Daniel","Daniel Gibbes","Saint-Martin Saint-Barthélemy",1,"UMP","contre",1],
	  ["M.","Gilard","Franck","Franck Gilard","Eure",5,"UMP","contre",1],
	  ["M.","Gille","Jean-Patrick","Jean-Patrick Gille","Indre-et-Loire",1,"SRC","pour",1],
	  ["M.","Ginesta","Jordi Dit Georges","Jordi Dit Georges Ginesta","Var",5,"UMP","contre",1],
	  ["M.","Ginesy","Charles Ange","Charles Ange Ginesy","Alpes-Maritimes",2,"UMP","contre",1],
	  ["M.","Giran","Jean-Pierre","Jean-Pierre Giran","Var",3,"UMP","contre",1],
	  ["Mme","Girardin","Annick","Annick Girardin","Saint-Pierre-et-Miquelon",1,"RRDP","pour",1],
	  ["M.","Giraud","Joël","Joël Giraud","Hautes-Alpes",2,"RRDP","pour",1],
	  ["M.","Glavany","Jean","Jean Glavany","Hautes-Pyrénées",1,"SRC","pour",1],
	  ["M.","Goasdoué","Yves","Yves Goasdoué","Orne",3,"SRC","pour",1],
	  ["M.","Goasguen","Claude","Claude Goasguen","Paris",14,"UMP","contre",1],
	  ["M.","Goldberg","Daniel","Daniel Goldberg","Seine-Saint-Denis",10,"SRC","pour",1],
	  ["M.","Gomès","Philippe","Philippe Gomès","Nouvelle-Calédonie",2,"UDI","pour",1],
	  ["M.","Gorges","Jean-Pierre","Jean-Pierre Gorges","Eure-et-Loir",1,"UMP","contre",1],
	  ["M.","Gosselin","Philippe","Philippe Gosselin","Manche",1,"UMP","contre",1],
	  ["M.","Gosselin-Fleury","Geneviève","Geneviève Gosselin-Fleury","Manche",4,"SRC","pour",1],
	  ["Mme","Got","Pascale","Pascale Got","Gironde",5,"SRC","pour",1],
	  ["M.","Goua","Marc","Marc Goua","Maine-et-Loire",2,"SRC","pour",1],
	  ["M.","Goujon","Philippe","Philippe Goujon","Paris",12,"UMP","contre",1],
	  ["Mme","Gourjade","Linda","Linda Gourjade","Tarn",3,"SRC","pour",1],
	  ["M.","Grandguillaume","Laurent","Laurent Grandguillaume","Côte-d'Or",1,"SRC","pour",1],
	  ["Mme","Greff","Claude","Claude Greff","Indre-et-Loire",2,"UMP","contre",1],
	  ["Mme","Grelier","Estelle","Estelle Grelier","Seine-Maritime",9,"SRC","pour",1],
	  ["M.","Grellier","Jean","Jean Grellier","Deux-Sèvres",3,"SRC","pour",1],
	  ["Mme","Grommerch","Anne","Anne Grommerch","Moselle",9,"UMP","contre",1],
	  ["Mme","Grosskost","Arlette","Arlette Grosskost","Haut-Rhin",5,"UMP","contre",1],
	  ["M.","Grouard","Serge","Serge Grouard","Loiret",2,"UMP","contre",1],
	  ["M.","Guaino","Henri","Henri Guaino","Yvelines",3,"UMP","contre",1],
	  ["M.","Guedj","Jérôme","Jérôme Guedj","Essonne",6,"SRC","pour",1],
	  ["Mme","Guégot","Françoise","Françoise Guégot","Seine-Maritime",2,"UMP","contre",1],
	  ["Mme","Gueugneau","Edith","Edith Gueugneau","Saône-et-Loire",2,"SRC","pour",1],
	  ["M.","Guibal","Jean-Claude","Jean-Claude Guibal","Alpes-Maritimes",4,"UMP","contre",1],
	  ["Mme","Guigou","Elisabeth","Elisabeth Guigou","Seine-Saint-Denis",6,"SRC","pour",1],
	  ["Mme","Guilbert","Thérèse","Thérèse Guilbert","Pas-de-Calais",5,"SRC","pour",1],
	  ["M.","Guillet","Jean-Jacques","Jean-Jacques Guillet","Hauts-de-Seine",8,"UMP","contre",1],
	  ["M.","Guilloteau","Christophe","Christophe Guilloteau","Rhône",10,"UMP","contre",1],
	  ["Mme","Guittet","Chantal","Chantal Guittet","Finistère",5,"SRC","pour",1],
	  ["M.","Habib","David","David Habib","Pyrénées-Atlantiques",3,"SRC","pour",1],
	  ["M.","Hammadi","Razzy","Razzy Hammadi","Seine-Saint-Denis",7,"SRC","pour",1],
	  ["M.","Hanotin","Mathieu","Mathieu Hanotin","Seine-Saint-Denis",2,"SRC","pour",1],
	  ["M.","Heinrich","Michel","Michel Heinrich","Vosges",1,"UMP","contre",1],
	  ["M.","Herbillon","Michel","Michel Herbillon","Val-de-Marne",8,"UMP","contre",1],
	  ["M.","Herth","Antoine","Antoine Herth","Bas-Rhin",5,"UMP","contre",1],
	  ["M.","Hetzel","Patrick","Patrick Hetzel","Bas-Rhin",7,"UMP","contre",1],
	  ["M.","Hillmeyer","Francis","Francis Hillmeyer","Haut-Rhin",6,"UDI","contre",1],
	  ["Mme","Hoffman-Rispal","Daniele","Daniele Hoffman-Rispal","Paris",6,"SRC","pour",1],
	  ["M.","Houillon","Philippe","Philippe Houillon","Val-d'Oise",1,"UMP","contre",1],
	  ["M.","Huet","Guenhael","Guenhael Huet","Manche",2,"UMP","contre",1],
	  ["Mme","Huillier","Joëlle","Joëlle Huillier","Isère",10,"SRC","pour",1],
	  ["Mme","Hurel","Sandrine","Sandrine Hurel","Seine-Maritime",6,"SRC","pour",1],
	  ["M.","Hutin","Christian","Christian Hutin","Nord",13,"SRC","pour",1],
	  ["M.","Huyghe","Sébastien","Sébastien Huyghe","Nord",5,"UMP","contre",1],
	  ["Mme","Iborra","Monique","Monique Iborra","Haute-Garonne",6,"SRC","pour",1],
	  ["Mme","Imbert","Françoise","Françoise Imbert","Haute-Garonne",5,"SRC","pour",1],
	  ["M.","Issindou","Michel","Michel Issindou","Isère",2,"SRC","pour",1],
	  ["M.","Jacob","Christian","Christian Jacob","Seine-et-Marne",4,"UMP","contre",1],
	  ["M.","Jacquat","Denis","Denis Jacquat","Moselle",2,"UMP","contre",1],
	  ["M.","Jalton","Eric","Eric Jalton","Guadeloupe",1,"SRC","pour",1],
	  ["M.","Janquin","Serge","Serge Janquin","Pas-de-Calais",10,"SRC","pour",1],
	  ["M.","Jégo","Yves","Yves Jégo","Seine-et-Marne",3,"UDI","pour",1],
	  ["M.","Jibrayel","Henri","Henri Jibrayel","Bouches-du-Rhône",7,"SRC","pour",1],
	  ["M.","Juanico","Régis","Régis Juanico","Loire",1,"SRC","pour",1],
	  ["M.","Jung","Armand","Armand Jung","Bas-Rhin",1,"SRC","pour",1],
	  ["M.","Kalinowski","Laurent","Laurent Kalinowski","Moselle",6,"SRC","pour",1],
	  ["Mme","Karamanli","Marietta","Marietta Karamanli","Sarthe",2,"SRC","pour",1],
	  ["M.","Kemel","Philippe","Philippe Kemel","Pas-de-Calais",11,"SRC","pour",1],
	  ["M.","Kert","Christian","Christian Kert","Bouches-du-Rhône",11,"UMP","contre",1],
	  ["Mme","Khirouni","Chaynesse","Chaynesse Khirouni","Meurthe-et-Moselle",1,"SRC","pour",1],
	  ["Mme","Kosciusko-Morizet","Nathalie","Nathalie Kosciusko-Morizet","Essonne",4,"UMP","abstention",1],
	  ["M.","Kossowski","Jacques","Jacques Kossowski","Hauts-de-Seine",3,"UMP","contre",1],
	  ["M.","Krabal","Jacques","Jacques Krabal","Aisne",5,"RRDP","pour",1],
	  ["M.","Labaune","Patrick","Patrick Labaune","Drôme",1,"UMP","contre",1],
	  ["Mme","Laclais","Bernadette","Bernadette Laclais","Savoie",4,"SRC","contre",1],
	  ["Mme","Lacroute","Valérie","Valérie Lacroute","Seine-et-Marne",2,"UMP","contre",1],
	  ["Mme","Lacuey","Conchita","Conchita Lacuey","Gironde",4,"SRC","pour",1],
	  ["M.","Laffineur","Marc","Marc Laffineur","Maine-et-Loire",7,"UMP","contre",1],
	  ["Mme","Lagarde","Sonia","Sonia Lagarde","Nouvelle-Calédonie",1,"UDI","pour",1],
	  ["M.","Lagarde","Jean-Christophe","Jean-Christophe Lagarde","Seine-Saint-Denis",5,"UDI","pour",1],
	  ["M.","Lambert","Jérôme","Jérôme Lambert","Charente",3,"SRC","contre",1],
	  ["M.","Lambert","François-Michel","François-Michel Lambert","Bouches-du-Rhône",10,"ECOLO","pour",1],
	  ["M.","Lamblin","Jacques","Jacques Lamblin","Meurthe-et-Moselle",4,"UMP","contre",1],
	  ["M.","Lamour","Jean-François","Jean-François Lamour","Paris",13,"UMP","contre",1],
	  ["Mme","Langlade","Colette","Colette Langlade","Dordogne",3,"SRC","pour",1],
	  ["M.","Larrivé","Guillaume","Guillaume Larrivé","Yonne",1,"UMP","contre",1],
	  ["M.","Lassalle","Jean","Jean Lassalle","Pyrénées-Atlantiques",4,"NI","contre",1],
	  ["M.","Launay","Jean","Jean Launay","Lot",2,"SRC","pour",1],
	  ["M.","Laurent","Jean-Luc","Jean-Luc Laurent","Val-de-Marne",10,"SRC","abstention",1],
	  ["M.","Lazaro","Thierry","Thierry Lazaro","Nord",6,"UMP","contre",1],
	  ["M.","Le Borgn'","Pierre-Yves","Pierre-Yves Le Borgn'","Français de l'étranger",7,"SRC","pour",1],
	  ["M.","Le Bouillonnec","Jean-Yves","Jean-Yves Le Bouillonnec","Val-de-Marne",11,"SRC","pour",1],
	  ["M.","Le Bris","Gilbert","Gilbert Le Bris","Finistère",8,"SRC","pour",1],
	  ["Mme","Le Callennec","Isabelle","Isabelle Le Callennec","Ille-et-Vilaine",5,"UMP","contre",1],
	  ["Mme","Le Dain","Anne-Yvonne","Anne-Yvonne Le Dain","Hérault",2,"SRC","pour",1],
	  ["M.","Le Déaut","Jean-Yves","Jean-Yves Le Déaut","Meurthe-et-Moselle",6,"SRC","pour",1],
	  ["Mme","Le Dissez","Viviane","Viviane Le Dissez","Côtes-d'Armor",2,"SRC","pour",1],
	  ["M.","Le Fur","Marc","Marc Le Fur","Côtes-d'Armor",3,"UMP","contre",1],
	  ["M.","Le Guen","Jean-Marie","Jean-Marie Le Guen","Paris",9,"SRC","pour",1],
	  ["Mme","Le Houérou","Annie","Annie Le Houérou","Côtes-d'Armor",4,"SRC","pour",1],
	  ["Mme","Le Loch","Annick","Annick Le Loch","Finistère",7,"SRC","pour",1],
	  ["M.","Le Maire","Bruno","Bruno Le Maire","Eure",1,"UMP","abstention",1],
	  ["M.","Le Mèner","Dominique","Dominique Le Mèner","Sarthe",5,"UMP","contre",1],
	  ["M.","Le Ray","Philippe","Philippe Le Ray","Morbihan",2,"UMP","contre",1],
	  ["M.","Le Roch","Jean-Pierre","Jean-Pierre Le Roch","Morbihan",3,"SRC","pour",1],
	  ["M.","Le Roux","Bruno","Bruno Le Roux","Seine-Saint-Denis",1,"SRC","pour",1],
	  ["M","Léautey","Pierre","Pierre Léautey","Seine-Maritime",1,"SRC","pour",1],
	  ["M.","Leboeuf","Alain","Alain Leboeuf","Vendée",1,"UMP","contre",1],
	  ["M.","Lebreton","Patrick","Patrick Lebreton","La Réunion",4,"SRC","contre",1],
	  ["M.","Lefait","Michel","Michel Lefait","Pas-de-Calais",8,"SRC","pour",1],
	  ["M.","Lefebvre","Dominique","Dominique Lefebvre","Val-d'Oise",10,"SRC","pour",1],
	  ["M.","Lellouche","Pierre","Pierre Lellouche","Paris",1,"UMP","abstention",1],
	  ["Mme","Lemaire","Axelle","Axelle Lemaire","Français de l'étranger",3,"SRC","pour",1],
	  ["M.","Lemasle","Patrick","Patrick Lemasle","Haute-Garonne",7,"SRC","pour",1],
	  ["Mme","Lemorton","Catherine","Catherine Lemorton","Haute-Garonne",1,"SRC","pour",1],
	  ["M.","Léonard","Christophe","Christophe Léonard","Ardennes",2,"SRC","pour",1],
	  ["M.","Leonetti","Jean","Jean Leonetti","Alpes-Maritimes",7,"UMP","contre",1],
	  ["Mme","Lepetit","Annick","Annick Lepetit","Paris",3,"SRC","pour",1],
	  ["M.","Lequiller","Pierre","Pierre Lequiller","Yvelines",4,"UMP","contre",1],
	  ["M.","Leroy","Maurice","Maurice Leroy","Loir-et-Cher",3,"UDI","contre",1],
	  ["M.","Leroy","Arnaud","Arnaud Leroy","Français de l'étranger",5,"SRC","pour",1],
	  ["M.","Lesage","Michel","Michel Lesage","Côtes-d'Armor",1,"SRC","pour",1],
	  ["M.","Lesterlin","Bernard","Bernard Lesterlin","Allier",2,"SRC","pour",1],
	  ["M.","Letchimy","Serge","Serge Letchimy","Martinique",3,"SRC","pour",1],
	  ["M.","Lett","Céleste","Céleste Lett","Moselle",5,"UMP","contre",1],
	  ["Mme","Levy","Geneviève","Geneviève Levy","Var",1,"UMP","contre",1],
	  ["M.","Liebgott","Michel","Michel Liebgott","Moselle",8,"SRC","pour",1],
	  ["Mme","Lignières-Cassou","Martine","Martine Lignières-Cassou","Pyrénées-Atlantiques",1,"SRC","pour",1],
	  ["Mme","Linkenheld","Audrey","Audrey Linkenheld","Nord",2,"SRC","pour",1],
	  ["M.","Loncle","François","François Loncle","Eure",4,"SRC","pour",1],
	  ["Mme","Louis-Carabin","Gabrielle","Gabrielle Louis-Carabin","Guadeloupe",2,"SRC","contre",1],
	  ["Mme","Lousteau","Lucette","Lucette Lousteau","Lot-et-Garonne",1,"SRC","pour",1],
	  ["Mme","Louwagie","Véronique","Véronique Louwagie","Orne",2,"UMP","contre",1],
	  ["M.","Luca","Lionnel","Lionnel Luca","Alpes-Maritimes",6,"UMP","contre",1],
	  ["M.","Lurton","Gilles","Gilles Lurton","Ille-et-Vilaine",7,"UMP","contre",1],
	  ["M.","Maggi","Jean-Pierre","Jean-Pierre Maggi","Bouches-du-Rhône",8,"SRC","pour",1],
	  ["M.","Mallé","Jean-Philippe","Jean-Philippe Mallé","Yvelines",11,"SRC","abstention",1],
	  ["M.","Mamère","Noël","Noël Mamère","Gironde",3,"ECOLO","pour",1],
	  ["M.","Mancel","Jean-François","Jean-François Mancel","Oise",2,"UMP","contre",1],
	  ["M.","Mandon","Thierry","Thierry Mandon","Essonne",9,"SRC","pour",1],
	  ["Mme","Maquet","Jacqueline","Jacqueline Maquet","Pas-de-Calais",2,"SRC","pour",1],
	  ["M.","Marc","Alain","Alain Marc","Aveyron",3,"UMP","contre",1],
	  ["M.","Marcangeli","Laurent","Laurent Marcangeli","Corse-du-Sud",1,"UMP","contre",1],
	  ["Mme","Marcel","Marie-Lou","Marie-Lou Marcel","Aveyron",2,"SRC","pour",1],
	  ["Mme","Maréchal-Le Pen","Marion","Marion Maréchal-Le Pen","Vaucluse",3,"NI","contre",1],
	  ["M.","Mariani","Thierry","Thierry Mariani","Français de l'étranger",11,"UMP","contre",1],
	  ["M.","Marie-Jeanne","Alfred","Alfred Marie-Jeanne","Martinique",1,"GDR","contre",1],
	  ["M.","Mariton","Hervé","Hervé Mariton","Drôme",3,"UMP","contre",1],
	  ["M.","Marleix","Alain","Alain Marleix","Cantal",2,"UMP","contre",1],
	  ["M.","Marleix","Olivier","Olivier Marleix","Eure-et-Loir",2,"UMP","contre",1],
	  ["M.","Marlin","Franck","Franck Marlin","Essonne",2,"UMP","contre",1],
	  ["M.","Marsac","Jean-René","Jean-René Marsac","Ille-et-Vilaine",4,"SRC","pour",1],
	  ["M.","Marsaud","Alain","Alain Marsaud","Français de l'étranger",10,"UMP","contre",1],
	  ["M.","Martin","Philippe","Philippe Martin","Marne",3,"UMP","contre",1],
	  ["M.","Martin","Philippe","Philippe Martin","Gers",1,"SRC","pour",1],
	  ["M.","Martin-Lalande","Patrice","Patrice Martin-Lalande","Loir-et-Cher",2,"UMP","contre",1],
	  ["Mme","Martinel","Martine","Martine Martinel","Haute-Garonne",4,"SRC","pour",1],
	  ["M.","Marty","Alain","Alain Marty","Moselle",4,"UMP","contre",1],
	  ["Mme","Massat","Fréderique","Fréderique Massat","Ariège",1,"SRC","pour",1],
	  ["Mme","Massonneau","Véronique","Véronique Massonneau","Vienne",4,"ECOLO","pour",1],
	  ["M.","Mathis","Jean-Claude","Jean-Claude Mathis","Aube",2,"UMP","contre",1],
	  ["Mme","Mazetier","Sandrine","Sandrine Mazetier","Paris",8,"SRC","pour",1],
	  ["M.","Ménard","Michel","Michel Ménard","Loire-Atlantique",5,"SRC","pour",1],
	  ["M.","Mennucci","Patrick","Patrick Mennucci","Bouches-du-Rhône",4,"SRC","pour",1],
	  ["M.","Meslot","Damien","Damien Meslot","Territoire de Belfort",1,"UMP","contre",1],
	  ["M.","Mesquida","Kléber","Kléber Mesquida","Hérault",5,"SRC","pour",1],
	  ["M.","Meunier","Philippe","Philippe Meunier","Rhône",13,"UMP","contre",1],
	  ["M.","Mignon","Jean-Claude","Jean-Claude Mignon","Seine-et-Marne",1,"UMP","contre",1],
	  ["M","Moignard","Jacques","Jacques Moignard","Tarn-et-Garonne",2,"RRDP","pour",1],
	  ["M.","Molac","Paul","Paul Molac","Morbihan",4,"ECOLO","pour",1],
	  ["M.","Morange","Pierre","Pierre Morange","Yvelines",6,"UMP","contre",1],
	  ["M.","Moreau","Yannick","Yannick Moreau","Vendée",3,"NI","contre",1],
	  ["M.","Morel-A-L'Huissier","Pierre","Pierre Morel-A-L'Huissier","Lozère",1,"UMP","contre",1],
	  ["M.","Morin","Hervé","Hervé Morin","Eure",3,"UDI","contre",1],
	  ["M.","Moudenc","Jean-Luc","Jean-Luc Moudenc","Haute-Garonne",3,"UMP","contre",1],
	  ["M.","Moyne-Bressand","Alain","Alain Moyne-Bressand","Isère",6,"UMP","contre",1],
	  ["M.","Muet","Pierre-Alain","Pierre-Alain Muet","Rhône",2,"SRC","pour",1],
	  ["M.","Myard","Jacques","Jacques Myard","Yvelines",5,"UMP","contre",1],
	  ["Mme","Nachury","Dominique","Dominique Nachury","Rhône",4,"UMP","contre",1],
	  ["M.","Nauche","Philippe","Philippe Nauche","Corrèze",2,"SRC","pour",1],
	  ["Mme","Neuville","Ségolène","Ségolène Neuville","Pyrénées-Orientales",3,"SRC","pour",1],
	  ["M.","Nicolin","Yves","Yves Nicolin","Loire",5,"UMP","contre",1],
	  ["Mme","Nieson","Nathalie","Nathalie Nieson","Drôme",4,"SRC","pour",1],
	  ["M.","Nilor","Jean-Philippe","Jean-Philippe Nilor","Martinique",4,"GDR","contre",1],
	  ["M.","Noguès","Philippe","Philippe Noguès","Morbihan",6,"SRC","pour",1],
	  ["Mme","Olivier","Maud","Maud Olivier","Essonne",5,"SRC","pour",1],
	  ["M.","Ollier","Patrick","Patrick Ollier","Hauts-de-Seine",7,"UMP","contre",1],
	  ["Mme","Orliac","Dominique","Dominique Orliac","Lot",1,"RRDP","pour",1],
	  ["Mme","Orphé","Monique","Monique Orphé","La Réunion",6,"SRC","pour",1],
	  ["M.","Pajon","Michel","Michel Pajon","Seine-Saint-Denis",3,"SRC","pour",1],
	  ["M.","Pancher","Bertrand","Bertrand Pancher","Meuse",1,"UDI","contre",1],
	  ["Mme","Pane","Luce","Luce Pane","Seine-Maritime",3,"SRC","pour",1],
	  ["M.","Paul","Christian","Christian Paul","Nièvre",2,"SRC","pour",1],
	  ["M.","Pauvros","Rémi","Rémi Pauvros","Nord",3,"SRC","pour",1],
	  ["Mme","Pécresse","Valérie","Valérie Pécresse","Yvelines",2,"UMP","contre",1],
	  ["M.","Peiro","Germinal","Germinal Peiro","Dordogne",4,"SRC","pour",1],
	  ["M.","Pélissard","Jacques","Jacques Pélissard","Jura",1,"UMP","contre",1],
	  ["M.","Pellois","Hervé","Hervé Pellois","Morbihan",1,"SRC","pour",1],
	  ["M.","Perez","Jean-Claude","Jean-Claude Perez","Aude",1,"SRC","pour",1],
	  ["M.","Perrut","Bernard","Bernard Perrut","Rhône",9,"UMP","contre",1],
	  ["M.","Philippe","Edouard","Edouard Philippe","Seine-Maritime",7,"UMP","abstention",1],
	  ["Mme","Pichot ","Sylvie","Sylvie Pichot ","Mayenne",1,"SRC","pour",1],
	  ["M.","Pietrasanta","Sébastien","Sébastien Pietrasanta","Hauts-de-Seine",2,"SRC","pour",1],
	  ["Mme","Pinville","Martine","Martine Pinville","Charente",1,"SRC","pour",1],
	  ["Mme","Pires Beaune","Christine","Christine Pires Beaune","Puy-de-Dôme",2,"SRC","pour",1],
	  ["M.","Piron","Michel","Michel Piron","Maine-et-Loire",4,"UDI","contre",1],
	  ["M.","Plisson","Philippe","Philippe Plisson","Gironde",11,"SRC","pour",1],
	  ["Mme","Pochon","Elisabeth","Elisabeth Pochon","Seine-Saint-Denis",8,"SRC","pour",1],
	  ["M.","Poisson","Jean-Frédéric","Jean-Frédéric Poisson","Yvelines",10,"UMP","contre",1],
	  ["Mme","Poletti","Bérengère","Bérengère Poletti","Ardennes",1,"UMP","contre",1],
	  ["Mme","Pompili","Barbara","Barbara Pompili","Somme",2,"ECOLO","pour",1],
	  ["M.","Poniatowski","Axel","Axel Poniatowski","Val-d'Oise",2,"UMP","contre",1],
	  ["Mme","Pons","Josette","Josette Pons","Var",6,"UMP","contre",1],
	  ["M.","Popelin","Pascal","Pascal Popelin","Seine-Saint-Denis",12,"SRC","pour",1],
	  ["M.","Potier","Dominique","Dominique Potier","Meurthe-et-Moselle",5,"SRC","abstention",1],
	  ["Mme","Poumirol","Emilienne","Emilienne Poumirol","Haute-Garonne",10,"SRC","pour",1],
	  ["M.","Pouzol","Michel","Michel Pouzol","Essonne",3,"SRC","pour",1],
	  ["M.","Prat","Patrice","Patrice Prat","Gard",3,"SRC","pour",1],
	  ["M.","Priou","Christophe","Christophe Priou","Loire-Atlantique",7,"UMP","contre",1],
	  ["M.","Pueyo","Joaquim","Joaquim Pueyo","Orne",1,"SRC","pour",1],
	  ["M.","Pupponi","François","François Pupponi","Val-d'Oise",8,"SRC","-",1],
	  ["M.","Quentin","Didier","Didier Quentin","Charente-Maritime",5,"UMP","contre",1],
	  ["Mme","Quéré","Catherine","Catherine Quéré","Charente-Maritime",3,"SRC","pour",1],
	  ["Mme","Rabault","Valérie","Valérie Rabault","Tarn-et-Garonne",1,"SRC","pour",1],
	  ["Mme","Rabin","Monique","Monique Rabin","Loire-Atlantique",9,"SRC","pour",1],
	  ["M.","Raimbourg","Dominique","Dominique Raimbourg","Loire-Atlantique",4,"SRC","pour",1],
	  ["Mme","Récalde","Marie","Marie Récalde","Gironde",6,"SRC","pour",1],
	  ["M.","Reiss","Frédéric","Frédéric Reiss","Bas-Rhin",8,"UMP","contre",1],
	  ["M.","Reitzer","Jean-Luc","Jean-Luc Reitzer","Haut-Rhin",3,"UMP","contre",1],
	  ["Mme","Reynaud","Marie-Line","Marie-Line Reynaud","Charente",2,"SRC","pour",1],
	  ["M.","Reynès","Bernard","Bernard Reynès","Bouches-du-Rhône",15,"UMP","contre",1],
	  ["M.","Reynier","Franck","Franck Reynier","Drôme",2,"UDI","contre",1],
	  ["M.","Richard","Arnaud","Arnaud Richard","Yvelines",7,"UDI","contre",1],
	  ["M.","Riester","Franck","Franck Riester","Seine-et-Marne",5,"UMP","pour",1],
	  ["M.","Rihan Cypel","Eduardo","Eduardo Rihan Cypel","Seine-et-Marne",8,"SRC","pour",1],
	  ["M.","Robert","Thierry","Thierry Robert","La Réunion",7,"RRDP","contre",1],
	  ["M.","Robiliard","Denys","Denys Robiliard","Loir-et-Cher",1,"SRC","pour",1],
	  ["M.","Robinet","Arnaud","Arnaud Robinet","Marne",1,"UMP","contre",1],
	  ["M.","Rochebloine","François","François Rochebloine","Loire",3,"UDI","contre",1],
	  ["M.","Rodet","Alain","Alain Rodet","Haute-Vienne",1,"SRC","pour",1],
	  ["M.","Rogemont","Marcel","Marcel Rogemont","Ille-et-Vilaine",8,"SRC","pour",1],
	  ["Mme","Rohfritsch","Sophie","Sophie Rohfritsch","Bas-Rhin",4,"UMP","contre",1],
	  ["M.","Roig","Frédéric","Frédéric Roig","Hérault",4,"SRC","pour",1],
	  ["Mme","Romagnan","Barbara","Barbara Romagnan","Doubs",1,"SRC","pour",1],
	  ["M.","Roman","Bernard","Bernard Roman","Nord",1,"SRC","pour",1],
	  ["M.","Rouillard","Gwendal","Gwendal Rouillard","Morbihan",5,"SRC","pour",1],
	  ["M.","Roumégas","Jean-Louis","Jean-Louis Roumégas","Hérault",1,"ECOLO","pour",1],
	  ["M.","Rouquet","René","René Rouquet","Val-de-Marne",9,"SRC","pour",1],
	  ["M.","Rousset","Alain","Alain Rousset","Gironde",7,"SRC","pour",1],
	  ["M.","Saddier","Martial","Martial Saddier","Haute-Savoie",3,"UMP","contre",1],
	  ["M.","Said","Boinali","Boinali Said","Mayotte",1,"SRC","pour",1],
	  ["M.","Saint-André","Stéphane","Stéphane Saint-André","Pas-de-Calais",9,"RRDP","pour",1],
	  ["M.","Salen","Paul","Paul Salen","Loire",6,"UMP","contre",1],
	  ["M.","Salles","Rudy","Rudy Salles","Alpes-Maritimes",3,"UDI","contre",1],
	  ["M.","Sansu","Nicolas","Nicolas Sansu","Cher",2,"GDR","pour",1],
	  ["Mme","Santais","Béatrice","Béatrice Santais","Savoie",3,"SRC","pour",1],
	  ["M.","Santini","André","André Santini","Hauts-de-Seine",10,"UDI","contre",1],
	  ["Mme","Sas","Eva","Eva Sas","Essonne",7,"ECOLO","pour",1],
	  ["Mme","Saugues","Odile","Odile Saugues","Puy-de-Dôme",1,"SRC","pour",1],
	  ["M.","Sauvadet","François","François Sauvadet","Côte-d'Or",4,"UDI","contre",1],
	  ["M.","Sauvan","Gilbert","Gilbert Sauvan","Alpes-de-Haute-Provence",1,"SRC","pour",1],
	  ["M.","Savary","Gilles","Gilles Savary","Gironde",9,"SRC","pour",1],
	  ["M.","Scellier","François","François Scellier","Val-d'Oise",6,"UMP","contre",1],
	  ["Mme","Schmid","Claudine","Claudine Schmid","Français de l'étranger",6,"UMP","contre",1],
	  ["M.","Schneider","André","André Schneider","Bas-Rhin",3,"UMP","contre",1],
	  ["M.","Schwartzenberg","Roger-Gérard","Roger-Gérard Schwartzenberg","Val-de-Marne",3,"RRDP","pour",1],
	  ["M.","Sebaoun","Gérard","Gérard Sebaoun","Val-d'Oise",4,"SRC","pour",1],
	  ["M.","Sermier","Jean-Marie","Jean-Marie Sermier","Jura",3,"UMP","contre",1],
	  ["M.","Serville","Gabriel","Gabriel Serville","Guyane",1,"GDR","abstention",1],
	  ["M.","Siré","Fernand","Fernand Siré","Pyrénées-Orientales",2,"UMP","contre",1],
	  ["M.","Sirugue","Christophe","Christophe Sirugue","Saône-et-Loire",5,"SRC","pour",1],
	  ["M.","Solère","Thierry","Thierry Solère","Hauts-de-Seine",9,"UMP","contre",1],
	  ["Mme","Sommaruga","Julie","Julie Sommaruga","Hauts-de-Seine",11,"SRC","pour",1],
	  ["M.","Sordi","Michel","Michel Sordi","Haut-Rhin",4,"UMP","contre",1],
	  ["M.","Straumann","Eric","Eric Straumann","Haut-Rhin",1,"UMP","contre",1],
	  ["M.","Sturni","Claude","Claude Sturni","Bas-Rhin",9,"UMP","contre",1],
	  ["M.","Suguenot","Alain","Alain Suguenot","Côte-d'Or",5,"UMP","contre",1],
	  ["Mme","Tabarot","Michele","Michele Tabarot","Alpes-Maritimes",9,"UMP","contre",1],
	  ["M.","Tahuaitu","Jonas","Jonas Tahuaitu","Polynésie Française",2,"UDI","contre",1],
	  ["Mme","Tallard","Suzanne","Suzanne Tallard","Charente-Maritime",2,"SRC","pour",1],
	  ["M.","Tardy","Lionel","Lionel Tardy","Haute-Savoie",2,"UMP","contre",1],
	  ["M.","Taugourdeau","Jean-Charles","Jean-Charles Taugourdeau","Maine-et-Loire",3,"UMP","contre",1],
	  ["M.","Teissier","Guy","Guy Teissier","Bouches-du-Rhône",6,"UMP","contre",1],
	  ["M.","Terrasse","Pascal","Pascal Terrasse","Ardèche",1,"SRC","pour",1],
	  ["M","Terrier","Gérard","Gérard Terrier","Moselle",1,"SRC","pour",1],
	  ["M.","Terrot","Michel","Michel Terrot","Rhône",12,"UMP","contre",1],
	  ["M.","Tetart","Jean-Marie","Jean-Marie Tetart","Yvelines",9,"UMP","contre",1],
	  ["M.","Thévenoud","Thomas","Thomas Thévenoud","Saône-et-Loire",1,"SRC","pour",1],
	  ["M.","Tian","Dominique","Dominique Tian","Bouches-du-Rhône",2,"UMP","contre",1],
	  ["Mme","Tolmont","Sylvie","Sylvie Tolmont","Sarthe",4,"SRC","pour",1],
	  ["M.","Touraine","Jean-Louis","Jean-Louis Touraine","Rhône",3,"SRC","pour",1],
	  ["M.","Tourret","Alain","Alain Tourret","Calvados",6,"RRDP","pour",1],
	  ["M.","Travert","Stéphane","Stéphane Travert","Manche",3,"SRC","pour",1],
	  ["Mme","Troallic","Catherine","Catherine Troallic","Seine-Maritime",8,"SRC","pour",1],
	  ["M.","Tuaiva","Jean-Paul","Jean-Paul Tuaiva","Polynésie Française",3,"UDI","contre",1],
	  ["Mme","Untermaier","Cécile","Cécile Untermaier","Saône-et-Loire",4,"SRC","pour",1],
	  ["M.","Urvoas","Jean-Jacques","Jean-Jacques Urvoas","Finistère",1,"SRC","pour",1],
	  ["M.","Vaillant","Daniel","Daniel Vaillant","Paris",17,"SRC","pour",1],
	  ["Mme","Vainqueur-Christohpe","Hélène","Hélène Vainqueur-Christohpe","Guadeloupe",4,"SRC","-",1],
	  ["M.","Valax","Jacques","Jacques Valax","Tarn",2,"SRC","pour",1],
	  ["Mme","Valter","Clotilde","Clotilde Valter","Calvados",3,"SRC","pour",1],
	  ["M.","Vannson","François","François Vannson","Vosges",3,"UMP","contre",1],
	  ["Mme","Vautrin","Catherine","Catherine Vautrin","Marne",2,"UMP","contre",1],
	  ["M.","Vauzelle","Michel","Michel Vauzelle","Bouches-du-Rhône",16,"SRC","pour",1],
	  ["M","Véran","Olivier","Olivier Véran","Isère",1,"SRC","pour",1],
	  ["M.","Vercamer","Francis","Francis Vercamer","Nord",7,"UDI","contre",1],
	  ["M.","Verchère","Patrice","Patrice Verchère","Rhône",8,"UMP","contre",1],
	  ["M.","Verdier","Fabrice","Fabrice Verdier","Gard",4,"SRC","pour",1],
	  ["M.","Vergnier","Michel","Michel Vergnier","Creuse",1,"SRC","pour",1],
	  ["M.","Vialatte","Jean-Sébastien","Jean-Sébastien Vialatte","Var",7,"UMP","contre",1],
	  ["M.","Vigier","Philippe","Philippe Vigier","Eure-et-Loir",4,"UDI","contre",1],
	  ["M.","Vigier","Jean-Pierre","Jean-Pierre Vigier","Haute-Loire",2,"UMP","contre",1],
	  ["M.","Vignal","Patrick","Patrick Vignal","Hérault",9,"SRC","pour",1],
	  ["M.","Villain","François-Xavier","François-Xavier Villain","Nord",18,"UDI","contre",1],
	  ["M.","Villaumé","Jean-Michel","Jean-Michel Villaumé","Haute-Saône",2,"SRC","pour",1],
	  ["M.","Vitel","Philippe","Philippe Vitel","Var",2,"UMP","contre",1],
	  ["M.","Vlody","Jean-Jacques","Jean-Jacques Vlody","La Réunion",3,"SRC","pour",1],
	  ["M.","Voisin","Michel","Michel Voisin","Ain",4,"UMP","contre",1],
	  ["M.","Warsmann","Jean-Luc","Jean-Luc Warsmann","Ardennes",3,"UMP","contre",1],
	  ["M.","Wauquiez","Laurent","Laurent Wauquiez","Haute-Loire",1,"UMP","contre",1],
	  ["M.","Woerth","Eric","Eric Woerth","Oise",4,"UMP","contre",1],
	  ["Mme","Zanetti","Paola","Paola Zanetti","Moselle",7,"SRC","pour",1],
	  ["Mme","Zimmermann","Marie-Jo","Marie-Jo Zimmermann","Moselle",3,"UMP","contre",1],
	  ["M.","Zumkeller","Michel","Michel Zumkeller","Territoire de Belfort",2,"UDI","contre",1]
]}